import React from 'react'
import PropTypes from 'prop-types'
import styled from 'styled-components'
import dynamic from 'next/dynamic'
import { useScreenshot } from './ScreenshotContext'

var supportedCountryCodes = [
  'ad', 'ae', 'af', 'ag', 'ai', 'al', 'am', 'ao', 'aq', 'ar', 'as', 'at', 'au',
  'aw', 'ax', 'az', 'ba', 'bb', 'bd', 'be', 'bf', 'bg', 'bh', 'bi', 'bj', 'bl',
  'bm', 'bn', 'bo', 'bq', 'br', 'bs', 'bt', 'bv', 'bw', 'by', 'bz', 'ca', 'cc',
  'cd', 'cf', 'cg', 'ch', 'ci', 'ck', 'cl', 'cm', 'cn', 'co', 'cr', 'cu', 'cv',
  'cw', 'cx', 'cy', 'cz', 'de', 'dj', 'dk', 'dm', 'do', 'dz', 'ec', 'ee', 'eg',
  'eh', 'er', 'es', 'et', 'eu', 'fi', 'fj', 'fk', 'fm', 'fo', 'fr', 'ga', 'gb',
  'gd', 'ge', 'gf', 'gg', 'gh', 'gi', 'gl', 'gm', 'gn', 'gp', 'gq', 'gr', 'gs',
  'gt', 'gu', 'gw', 'gy', 'hk', 'hm', 'hn', 'hr', 'ht', 'hu', 'id', 'ie', 'il',
  'im', 'in', 'io', 'iq', 'ir', 'is', 'it', 'je', 'jm', 'jo', 'jp', 'ke', 'kg',
  'kh', 'ki', 'km', 'kn', 'kp', 'kr', 'kw', 'ky', 'kz', 'la', 'lb', 'lc', 'li',
  'lk', 'lr', 'ls', 'lt', 'lu', 'lv', 'ly', 'ma', 'mc', 'md', 'me', 'mf', 'mg',
  'mh', 'mk', 'ml', 'mm', 'mn', 'mo', 'mp', 'mq', 'mr', 'ms', 'mt', 'mu', 'mv',
  'mw', 'mx', 'my', 'mz', 'na', 'nc', 'ne', 'nf', 'ng', 'ni', 'nl', 'no', 'np',
  'nr', 'nu', 'nz', 'om', 'pa', 'pe', 'pf', 'pg', 'ph', 'pk', 'pl', 'pm', 'pn',
  'pr', 'ps', 'pt', 'pw', 'py', 'qa', 're', 'ro', 'rs', 'ru', 'rw', 'sa', 'sb',
  'sc', 'sd', 'se', 'sg', 'sh', 'si', 'sj', 'sk', 'sl', 'sm', 'sn', 'so', 'sr',
  'ss', 'st', 'sv', 'sx', 'sy', 'sz', 'tc', 'td', 'tf', 'tg', 'th', 'tj', 'tk',
  'tl', 'tm', 'tn', 'to', 'tr', 'tt', 'tv', 'tw', 'tz', 'ua', 'ug', 'um', 'un',
  'us', 'uy', 'uz', 'va', 'vc', 've', 'vg', 'vi', 'vn', 'vu', 'wf', 'ws', 'ye',
  'yt', 'za', 'zm', 'zw']

const FlagImg = styled.img`
  width: ${props => props.size}px;
  height: ${props => props.size}px;
  clip-path: circle(50% at 50% 50%);
`
const FlagContainer = styled.div`
  border-radius: 50%;
  /* padding-left: 3px; */
  /* padding-top: 3px; */
  width: ${props => props.size + 6}px;
  height: ${props => props.size + 6}px;
  border: ${props => props.border ? '3px solid white' : 'none'};
  overflow: hidden;
  box-sizing: content-box;
`

const supportedFlagList = {
  'ad': dynamic(() => import('./flags/ad')),
  'ae': dynamic(() => import('./flags/ae')),
  'af': dynamic(() => import('./flags/af')),
  'ag': dynamic(() => import('./flags/ag')),
  'ai': dynamic(() => import('./flags/ai')),
  'al': dynamic(() => import('./flags/al')),
  'am': dynamic(() => import('./flags/am')),
  'ao': dynamic(() => import('./flags/ao')),
  'aq': dynamic(() => import('./flags/aq')),
  'ar': dynamic(() => import('./flags/ar')),
  'as': dynamic(() => import('./flags/as')),
  'at': dynamic(() => import('./flags/at')),
  'au': dynamic(() => import('./flags/au')),
  'aw': dynamic(() => import('./flags/aw')),
  'ax': dynamic(() => import('./flags/ax')),
  'az': dynamic(() => import('./flags/az')),
  'ba': dynamic(() => import('./flags/ba')),
  'bb': dynamic(() => import('./flags/bb')),
  'bd': dynamic(() => import('./flags/bd')),
  'be': dynamic(() => import('./flags/be')),
  'bf': dynamic(() => import('./flags/bf')),
  'bg': dynamic(() => import('./flags/bg')),
  'bh': dynamic(() => import('./flags/bh')),
  'bi': dynamic(() => import('./flags/bi')),
  'bj': dynamic(() => import('./flags/bj')),
  'bl': dynamic(() => import('./flags/bl')),
  'bm': dynamic(() => import('./flags/bm')),
  'bn': dynamic(() => import('./flags/bn')),
  'bo': dynamic(() => import('./flags/bo')),
  'bq': dynamic(() => import('./flags/bq')),
  'br': dynamic(() => import('./flags/br')),
  'bs': dynamic(() => import('./flags/bs')),
  'bt': dynamic(() => import('./flags/bt')),
  'bv': dynamic(() => import('./flags/bv')),
  'bw': dynamic(() => import('./flags/bw')),
  'by': dynamic(() => import('./flags/by')),
  'bz': dynamic(() => import('./flags/bz')),
  'ca': dynamic(() => import('./flags/ca')),
  'cc': dynamic(() => import('./flags/cc')),
  'cd': dynamic(() => import('./flags/cd')),
  'cf': dynamic(() => import('./flags/cf')),
  'cg': dynamic(() => import('./flags/cg')),
  'ch': dynamic(() => import('./flags/ch')),
  'ci': dynamic(() => import('./flags/ci')),
  'ck': dynamic(() => import('./flags/ck')),
  'cl': dynamic(() => import('./flags/cl')),
  'cm': dynamic(() => import('./flags/cm')),
  'cn': dynamic(() => import('./flags/cn')),
  'co': dynamic(() => import('./flags/co')),
  'cr': dynamic(() => import('./flags/cr')),
  'cu': dynamic(() => import('./flags/cu')),
  'cv': dynamic(() => import('./flags/cv')),
  'cw': dynamic(() => import('./flags/cw')),
  'cx': dynamic(() => import('./flags/cx')),
  'cy': dynamic(() => import('./flags/cy')),
  'cz': dynamic(() => import('./flags/cz')),
  'de': dynamic(() => import('./flags/de')),
  'dj': dynamic(() => import('./flags/dj')),
  'dk': dynamic(() => import('./flags/dk')),
  'dm': dynamic(() => import('./flags/dm')),
  'do': dynamic(() => import('./flags/do')),
  'dz': dynamic(() => import('./flags/dz')),
  'ec': dynamic(() => import('./flags/ec')),
  'ee': dynamic(() => import('./flags/ee')),
  'eg': dynamic(() => import('./flags/eg')),
  'eh': dynamic(() => import('./flags/eh')),
  'er': dynamic(() => import('./flags/er')),
  'es': dynamic(() => import('./flags/es')),
  'et': dynamic(() => import('./flags/et')),
  'eu': dynamic(() => import('./flags/eu')),
  'fi': dynamic(() => import('./flags/fi')),
  'fj': dynamic(() => import('./flags/fj')),
  'fk': dynamic(() => import('./flags/fk')),
  'fm': dynamic(() => import('./flags/fm')),
  'fo': dynamic(() => import('./flags/fo')),
  'fr': dynamic(() => import('./flags/fr')),
  'ga': dynamic(() => import('./flags/ga')),
  'gb': dynamic(() => import('./flags/gb')),
  'gd': dynamic(() => import('./flags/gd')),
  'ge': dynamic(() => import('./flags/ge')),
  'gf': dynamic(() => import('./flags/gf')),
  'gg': dynamic(() => import('./flags/gg')),
  'gh': dynamic(() => import('./flags/gh')),
  'gi': dynamic(() => import('./flags/gi')),
  'gl': dynamic(() => import('./flags/gl')),
  'gm': dynamic(() => import('./flags/gm')),
  'gn': dynamic(() => import('./flags/gn')),
  'gp': dynamic(() => import('./flags/gp')),
  'gq': dynamic(() => import('./flags/gq')),
  'gr': dynamic(() => import('./flags/gr')),
  'gs': dynamic(() => import('./flags/gs')),
  'gt': dynamic(() => import('./flags/gt')),
  'gu': dynamic(() => import('./flags/gu')),
  'gw': dynamic(() => import('./flags/gw')),
  'gy': dynamic(() => import('./flags/gy')),
  'hk': dynamic(() => import('./flags/hk')),
  'hm': dynamic(() => import('./flags/hm')),
  'hn': dynamic(() => import('./flags/hn')),
  'hr': dynamic(() => import('./flags/hr')),
  'ht': dynamic(() => import('./flags/ht')),
  'hu': dynamic(() => import('./flags/hu')),
  'id': dynamic(() => import('./flags/id')),
  'ie': dynamic(() => import('./flags/ie')),
  'il': dynamic(() => import('./flags/il')),
  'im': dynamic(() => import('./flags/im')),
  'in': dynamic(() => import('./flags/in')),
  'io': dynamic(() => import('./flags/io')),
  'iq': dynamic(() => import('./flags/iq')),
  'ir': dynamic(() => import('./flags/ir')),
  'is': dynamic(() => import('./flags/is')),
  'it': dynamic(() => import('./flags/it')),
  'je': dynamic(() => import('./flags/je')),
  'jm': dynamic(() => import('./flags/jm')),
  'jo': dynamic(() => import('./flags/jo')),
  'jp': dynamic(() => import('./flags/jp')),
  'ke': dynamic(() => import('./flags/ke')),
  'kg': dynamic(() => import('./flags/kg')),
  'kh': dynamic(() => import('./flags/kh')),
  'ki': dynamic(() => import('./flags/ki')),
  'km': dynamic(() => import('./flags/km')),
  'kn': dynamic(() => import('./flags/kn')),
  'kp': dynamic(() => import('./flags/kp')),
  'kr': dynamic(() => import('./flags/kr')),
  'kw': dynamic(() => import('./flags/kw')),
  'ky': dynamic(() => import('./flags/ky')),
  'kz': dynamic(() => import('./flags/kz')),
  'la': dynamic(() => import('./flags/la')),
  'lb': dynamic(() => import('./flags/lb')),
  'lc': dynamic(() => import('./flags/lc')),
  'li': dynamic(() => import('./flags/li')),
  'lk': dynamic(() => import('./flags/lk')),
  'lr': dynamic(() => import('./flags/lr')),
  'ls': dynamic(() => import('./flags/ls')),
  'lt': dynamic(() => import('./flags/lt')),
  'lu': dynamic(() => import('./flags/lu')),
  'lv': dynamic(() => import('./flags/lv')),
  'ly': dynamic(() => import('./flags/ly')),
  'ma': dynamic(() => import('./flags/ma')),
  'mc': dynamic(() => import('./flags/mc')),
  'md': dynamic(() => import('./flags/md')),
  'me': dynamic(() => import('./flags/me')),
  'mf': dynamic(() => import('./flags/mf')),
  'mg': dynamic(() => import('./flags/mg')),
  'mh': dynamic(() => import('./flags/mh')),
  'mk': dynamic(() => import('./flags/mk')),
  'ml': dynamic(() => import('./flags/ml')),
  'mm': dynamic(() => import('./flags/mm')),
  'mn': dynamic(() => import('./flags/mn')),
  'mo': dynamic(() => import('./flags/mo')),
  'mp': dynamic(() => import('./flags/mp')),
  'mq': dynamic(() => import('./flags/mq')),
  'mr': dynamic(() => import('./flags/mr')),
  'ms': dynamic(() => import('./flags/ms')),
  'mt': dynamic(() => import('./flags/mt')),
  'mu': dynamic(() => import('./flags/mu')),
  'mv': dynamic(() => import('./flags/mv')),
  'mw': dynamic(() => import('./flags/mw')),
  'mx': dynamic(() => import('./flags/mx')),
  'my': dynamic(() => import('./flags/my')),
  'mz': dynamic(() => import('./flags/mz')),
  'na': dynamic(() => import('./flags/na')),
  'nc': dynamic(() => import('./flags/nc')),
  'ne': dynamic(() => import('./flags/ne')),
  'nf': dynamic(() => import('./flags/nf')),
  'ng': dynamic(() => import('./flags/ng')),
  'ni': dynamic(() => import('./flags/ni')),
  'nl': dynamic(() => import('./flags/nl')),
  'no': dynamic(() => import('./flags/no')),
  'np': dynamic(() => import('./flags/np')),
  'nr': dynamic(() => import('./flags/nr')),
  'nu': dynamic(() => import('./flags/nu')),
  'nz': dynamic(() => import('./flags/nz')),
  'om': dynamic(() => import('./flags/om')),
  'pa': dynamic(() => import('./flags/pa')),
  'pe': dynamic(() => import('./flags/pe')),
  'pf': dynamic(() => import('./flags/pf')),
  'pg': dynamic(() => import('./flags/pg')),
  'ph': dynamic(() => import('./flags/ph')),
  'pk': dynamic(() => import('./flags/pk')),
  'pl': dynamic(() => import('./flags/pl')),
  'pm': dynamic(() => import('./flags/pm')),
  'pn': dynamic(() => import('./flags/pn')),
  'pr': dynamic(() => import('./flags/pr')),
  'ps': dynamic(() => import('./flags/ps')),
  'pt': dynamic(() => import('./flags/pt')),
  'pw': dynamic(() => import('./flags/pw')),
  'py': dynamic(() => import('./flags/py')),
  'qa': dynamic(() => import('./flags/qa')),
  're': dynamic(() => import('./flags/re')),
  'ro': dynamic(() => import('./flags/ro')),
  'rs': dynamic(() => import('./flags/rs')),
  'ru': dynamic(() => import('./flags/ru')),
  'rw': dynamic(() => import('./flags/rw')),
  'sa': dynamic(() => import('./flags/sa')),
  'sb': dynamic(() => import('./flags/sb')),
  'sc': dynamic(() => import('./flags/sc')),
  'sd': dynamic(() => import('./flags/sd')),
  'se': dynamic(() => import('./flags/se')),
  'sg': dynamic(() => import('./flags/sg')),
  'sh': dynamic(() => import('./flags/sh')),
  'si': dynamic(() => import('./flags/si')),
  'sj': dynamic(() => import('./flags/sj')),
  'sk': dynamic(() => import('./flags/sk')),
  'sl': dynamic(() => import('./flags/sl')),
  'sm': dynamic(() => import('./flags/sm')),
  'sn': dynamic(() => import('./flags/sn')),
  'so': dynamic(() => import('./flags/so')),
  'sr': dynamic(() => import('./flags/sr')),
  'ss': dynamic(() => import('./flags/ss')),
  'st': dynamic(() => import('./flags/st')),
  'sv': dynamic(() => import('./flags/sv')),
  'sx': dynamic(() => import('./flags/sx')),
  'sy': dynamic(() => import('./flags/sy')),
  'sz': dynamic(() => import('./flags/sz')),
  'tc': dynamic(() => import('./flags/tc')),
  'td': dynamic(() => import('./flags/td')),
  'tf': dynamic(() => import('./flags/tf')),
  'tg': dynamic(() => import('./flags/tg')),
  'th': dynamic(() => import('./flags/th')),
  'tj': dynamic(() => import('./flags/tj')),
  'tk': dynamic(() => import('./flags/tk')),
  'tl': dynamic(() => import('./flags/tl')),
  'tm': dynamic(() => import('./flags/tm')),
  'tn': dynamic(() => import('./flags/tn')),
  'to': dynamic(() => import('./flags/to')),
  'tr': dynamic(() => import('./flags/tr')),
  'tt': dynamic(() => import('./flags/tt')),
  'tv': dynamic(() => import('./flags/tv')),
  'tw': dynamic(() => import('./flags/tw')),
  'tz': dynamic(() => import('./flags/tz')),
  'ua': dynamic(() => import('./flags/ua')),
  'ug': dynamic(() => import('./flags/ug')),
  'um': dynamic(() => import('./flags/um')),
  'un': dynamic(() => import('./flags/un')),
  'us': dynamic(() => import('./flags/us')),
  'uy': dynamic(() => import('./flags/uy')),
  'uz': dynamic(() => import('./flags/uz')),
  'va': dynamic(() => import('./flags/va')),
  'vc': dynamic(() => import('./flags/vc')),
  've': dynamic(() => import('./flags/ve')),
  'vg': dynamic(() => import('./flags/vg')),
  'vi': dynamic(() => import('./flags/vi')),
  'vn': dynamic(() => import('./flags/vn')),
  'vu': dynamic(() => import('./flags/vu')),
  'wf': dynamic(() => import('./flags/wf')),
  'ws': dynamic(() => import('./flags/ws')),
  'ye': dynamic(() => import('./flags/ye')),
  'yt': dynamic(() => import('./flags/yt')),
  'za': dynamic(() => import('./flags/za')),
  'zm': dynamic(() => import('./flags/zm')),
  'zw': dynamic(() => import('./flags/zw')),
  'zz': dynamic(() => import('./flags/zz'))
}

export const Flag = ({countryCode, size, border}) => {
  const { isScreenshot } = useScreenshot()

  countryCode = countryCode.toLowerCase()
  if (supportedCountryCodes.indexOf(countryCode) === -1) {
    // Map unsupported country codes to ZZ
    countryCode = 'zz'
  }
  const FlagSvg = supportedFlagList[countryCode]
  const src = `/static/flags/1x1/${countryCode}.svg`
  return (
    <FlagContainer className='country-flag' size={size} border={border}>
      {isScreenshot ? (
        <FlagSvg size={size} />
      ):(
        <FlagImg src={src} size={size} />
      )}
    </FlagContainer>
  )
}

Flag.propTypes = {
  countryCode: PropTypes.string.isRequired,
  size: PropTypes.number.isRequired
}

Flag.defaultProps = {
  countryCode: 'zz',
  size: 60
}

export default Flag
