// Airport codes extracted from <https://github.com/jbrooksuk/JSON-Airports>
// License: MIT
export const AIRPORTS_PER_COUNTRY = [
  ['AD', ['alv']],
  ['AE', ['dcg', 'auh', 'azi', 'aan', 'dxb', 'nhd', 'dwc',
    'fjr', 'rkt', 'shj']],
  ['AF', ['olr', 'dwr', 'oaa', 'bin', 'bst', 'ccn', 'daz',
    'fah', 'fbd', 'kwh', 'hea', 'oai', 'jaa', 'kbl', 'kdh', 'kht', 'mmz', 'mzr',
    'lqn', 'oas', 'oah', 'sga', 'tii', 'und', 'oaz', 'zaj']],
  ['AG', ['anu',
    'bbq']],
  ['AI', ['axa']],
  ['AL', ['tia']],
  ['AM', ['lwn', 'evn']],
  ['AN',
    ['bon', 'cur', 'eux', 'sxm', 'sab']],
  ['AO', ['anl', 'cnz', 'drc', 'ggc', 'jmb',
    'knp', 'ndf', 'azz', 'ssy', 'bug', 'cab', 'cff', 'pgi', 'cbt', 'cti', 'cxm',
    'cav', 'due', 'vpe', 'nov', 'svp', 'lad', 'meg', 'spp', 'msz', 'gxg', 'pbn',
    'vhc', 'sza', 'ndd', 'ual', 'sdd', 'luo', 'ugo', 'ceo', 'xgn', 'arz']],
  ['AR',
    ['qrf', 'csz', 'cvi', 'cnt', 'vgs', 'lmd', 'szq', 'vcf', 'vme', 'ncj', 'cpg',
      'prq', 'lcp', 'mjr', 'cct', 'coc', 'ghu', 'jni', 'pra', 'ros', 'sfn', 'aep',
      'lcm', 'cor', 'fdo', 'lpg', 'epa', 'eze', 'hos', 'cvh', 'gnr', 'rds', 'apz',
      'mdz', 'lgs', 'afa', 'ctc', 'sde', 'rhd', 'irj', 'tuc', 'uaq', 'crr', 'rcu',
      'vdr', 'vme', 'rlo', 'luq', 'cnq', 'res', 'fma', 'igr', 'aol', 'mcs', 'pss',
      'psv', 'sla', 'juj', 'ora', 'ttg', 'clx', 'elo', 'oya', 'lls', 'mdx', 'rcq',
      'uzu', 'ehl', 'crd', 'emx', 'eqs', 'lhs', 'igb', 'oes', 'mqd', 'arr', 'sgv',
      'rel', 'vdm', 'pmy', 'ing', 'fte', 'pud', 'rga', 'rgl', 'ush', 'ula', 'roy',
      'pmq', 'ggs', 'jsm', 'ryo', 'rza', 'bhi', 'csz', 'ovr', 'gpo', 'oyo', 'sst',
      'mdq', 'nqn', 'nec', 'peh', 'rsa', 'brc', 'tdl', 'vlg', 'cut', 'cpc']],
  ['AS',
    ['tav', 'ofu', 'faq', 'ppg']],
  ['AT', ['hoh', 'grz', 'inn', 'klu', 'lnz', 'szg',
    'vie']],
  ['AU', ['agw', 'ayd', 'bck', 'bfc', 'bvw', 'byx', 'cob', 'cqp', 'crj',
    'cry', 'csd', 'ctr', 'dym', 'edd', 'ekd', 'hat', 'hig', 'his', 'hlv', 'kbd',
    'kgr', 'koh', 'kyf', 'lib', 'mnw', 'mup', 'mwy', 'myo', 'nkb', 'okb', 'pep',
    'rda', 'ssk', 'swb', 'tpr', 'twp', 'wrw', 'wsy', 'zvg', 'kfe', 'ltb', 'alh',
    'abg', 'awn', 'aud', 'mrp', 'axl', 'axc', 'ado', 'amx', 'amt', 'ayl', 'abh',
    'ary', 'gyl', 'arm', 'aab', 'auu', 'awp', 'avg', 'ayq', 'ayr', 'acf', 'abm',
    'bci', 'asp', 'bdd', 'bbe', 'bne', 'ool', 'bkq', 'cns', 'ctl', 'bxg', 'bvi',
    'btx', 'bqw', 'bhq', 'hti', 'beu', 'brk', 'buc', 'bln', 'lcn', 'bls', 'bqb',
    'isa', 'mcy', 'mky', 'bnk', 'bsj', 'gic', 'oky', 'bql', 'bmp', 'ppp', 'rok',
    'box', 'bme', 'bzd', 'bwq', 'bhs', 'brt', 'tsv', 'blt', 'bdb', 'buy', 'zbo',
    'wei', 'bwb', 'bvz', 'cgv', 'clh', 'cvq', 'csi', 'caz', 'coj', 'cby', 'cbi',
    'cpd', 'crb', 'ccl', 'cnc', 'cnj', 'cbx', 'cud', 'ced', 'cvc', 'cfi', 'llg',
    'cxt', 'cki', 'ctn', 'cmq', 'cma', 'cml', 'nif', 'ces', 'cnb', 'odl', 'cuq',
    'oom', 'cda', 'cww', 'cyg', 'cdq', 'kce', 'cmd', 'cug', 'cuy', 'cwr', 'ccw',
    'cwt', 'djr', 'dby', 'drn', 'dnb', 'drb', 'dfp', 'dlk', 'ddn', 'dlv', 'dmd',
    'dvr', 'nlf', 'drd', 'dvp', 'dpo', 'dhd', 'drr', 'dkv', 'dya', 'ech', 'euc',
    'etd', 'enb', 'eih', 'elc', 'emd', 'erb', 'epr', 'evd', 'evh', 'exm', 'frb',
    'kfe', 'fly', 'fls', 'fvl', 'fik', 'fos', 'fot', 'fiz', 'gah', 'gbl', 'guh',
    'goo', 'gdd', 'ggd', 'gts', 'get', 'gfn', 'gbv', 'glt', 'gul', 'glg', 'gex',
    'gli', 'glm', 'gvp', 'gpn', 'gte', 'gff', 'gtt', 'gee', 'gyp', 'hwk', 'hxx',
    'hvb', 'hub', 'hip', 'hid', 'hcq', 'hmg', 'hlt', 'hok', 'mhu', 'htu', 'hsm',
    'hgd', 'idk', 'ifl', 'iff', 'igh', 'ikp', 'inj', 'inm', 'ivw', 'isi', 'ivr',
    'jab', 'jun', 'qjd', 'jck', 'jur', 'ubu', 'kax', 'kby', 'kcs', 'kra', 'kns',
    'kbb', 'kfg', 'kkp', 'krb', 'kml', 'kps', 'kni', 'kwm', 'kgy', 'kgc', 'kug',
    'lwh', 'lgh', 'lno', 'lel', 'ldh', 'irg', 'ltp', 'ldc', 'lsy', 'loc', 'loa',
    'ltv', 'luu', 'lhg', 'lre', 'lut', 'ler', 'lvo', 'tgn', 'lzr', 'ubb', 'avv',
    'abx', 'mrg', 'mbb', 'xmc', 'mfp', 'mlr', 'dge', 'mqa', 'mkr', 'meb', 'mim',
    'sxe', 'mgt', 'mng', 'gsn', 'mgv', 'mqz', 'hba', 'mho', 'mcv', 'mql', 'xml',
    'mih', 'mtq', 'mjp', 'lst', 'mbw', 'mel', 'mmm', 'mtl', 'wme', 'onr', 'oxy',
    'mmg', 'oor', 'mrz', 'met', 'min', 'mqe', 'mov', 'rre', 'mwb', 'mya', 'mtd',
    'utb', 'mgb', 'ong', 'mnq', 'muq', 'mne', 'myi', 'mvk', 'mxu', 'mxd', 'mbh',
    'rty', 'nmr', 'nra', 'naa', 'rpm', 'nbh', 'nls', 'nac', 'qrm', 'rvt', 'nsv',
    'nsm', 'ntn', 'nur', 'nll', 'nub', 'zne', 'nyn', 'opi', 'xco', 'olp', 'odd',
    'moo', 'rbs', 'oag', 'odr', 'oso', 'oyn', 'adl', 'pug', 'pmk', 'pbo', 'pde',
    'drw', 'prd', 'beo', 'gov', 'ppi', 'jad', 'kta', 'kgi', 'pke', 'pkt', 'knx',
    'plo', 'lea', 'edr', 'pqq', 'ptj', 'phe', 'per', 'pea', 'ktr', 'umr', 'uir',
    'ulp', 'uee', 'rmk', 'rcm', 'ram', 'roh', 'rbu', 'rbc', 'rma', 'rsb', 'rts',
    'rtp', 'rhl', 'nds', 'bwu', 'cbr', 'cfs', 'cdu', 'nso', 'sqc', 'dbo', 'sgo',
    'six', 'zgl', 'sgp', 'dnm', 'jhq', 'sht', 'sbr', 'sio', 'shu', 'sth', 'snb',
    'noa', 'snh', 'scg', 'shq', 'ksv', 'srn', 'syd', 'hls', 'tmw', 'wga', 'swh',
    'swc', 'xtr', 'tbl', 'xto', 'taq', 'tbk', 'tdr', 'tef', 'tem', 'tan', 'xtg',
    'tyg', 'tyb', 'tky', 'tum', 'typ', 'thg', 'tca', 'tcw', 'tro', 'twb', 'uda',
    'czy', 'usl', 'vcd', 'vnr', 'wla', 'wav', 'wmb', 'syu', 'wio', 'wlc', 'waz',
    'wnd', 'wnr', 'wgt', 'wya', 'wit', 'wkb', 'wge', 'ntl', 'wun', 'wpk', 'wdi',
    'wol', 'qrr', 'wlo', 'win', 'wud', 'wew', 'wrw', 'wwi', 'wyn', 'bwt', 'ylg',
    'okr', 'kyf', 'xmy', 'yue', 'nga', 'orr', 'kyi']],
  ['AW', ['aua']],
  ['AZ',
    ['gyd', 'kvd', 'naj', 'gbb', 'ztu']],
  ['BA', ['bnx', 'omo', 'sjj', 'tzl']],
  ['BB', ['bgi']],
  ['BD', ['bzl', 'cxb', 'cla', 'cgp', 'ird', 'jsr', 'llj', 'rjh',
    'spd', 'tkr', 'zhm', 'zyl', 'dac']],
  ['BE', ['anr', 'bru', 'crl', 'kjk', 'lgg',
    'qnm', 'ost', 'qha', 'obl']],
  ['BF', ['xky', 'oug', 'xdj', 'xlu', 'pup', 'xbo',
    'xbg', 'dip', 'dor', 'fng', 'xgg', 'xka', 'tmq', 'xpa', 'arl', 'xse', 'teg',
    'xza', 'oua', 'bnr', 'dgu', 'xga', 'xnu', 'boy', 'tuq', 'xde', 'xar']],
  ['BG',
    ['hkv', 'jam', 'szr', 'boj', 'goz', 'pdv', 'pvn', 'sof', 'sls', 'szr', 'vid',
      'var']],
  ['BH', ['bah']],
  ['BI', ['bjm', 'gid']],
  ['BJ', ['coo', 'kdc', 'nae',
    'pko', 'svf']],
  ['BL', ['sbh']],
  ['BM', ['bda']],
  ['BN', ['bwn']],
  ['BO',
    ['rbq', 'bvl', 'mhw', 'apb', 'asc', 'bjo', 'cam', 'cbb', 'cij', 'cep', 'srz',
      'gya', 'bvk', 'sjs', 'sjb', 'sjv', 'lpb', 'mgd', 'oru', 'poi', 'pur', 'psz',
      'srd', 'rbo', 'rib', 'rey', 'sbl', 'srj', 'sng', 'snm', 'srb', 'sre', 'mqk',
      'tja', 'tdd', 'uyu', 'vah', 'vlm', 'vvi', 'byc']],
  ['BR', ['tuz', 'alt', 'swm',
    'ott', 'sb0', 'sb2', 'cdj', 'aps', 'aqa', 'aju', 'afl', 'aru', 'aax', 'bel',
    'bgx', 'plu', 'qak', 'bsb', 'bat', 'bau', 'bvb', 'bpg', 'bzc', 'cac', 'cfb',
    'itb', 'cnf', 'cgr', 'xap', 'cln', 'cks', 'ccm', 'clv', 'qns', 'caw', 'cmg',
    'cwb', 'crq', 'cxj', 'cgb', 'czs', 'ppb', 'mao', 'jcr', 'igu', 'fln', 'fen',
    'for', 'gig', 'gjm', 'gyn', 'gru', 'gpb', 'gvr', 'guj', 'atm', 'ita', 'itb',
    'ios', 'ipn', 'imp', 'jdf', 'jpa', 'jdo', 'joi', 'cpv', 'vcp', 'lec', 'laj',
    'lip', 'ldb', 'laz', 'mab', 'mqh', 'meu', 'mea', 'mgf', 'moc', 'mii', 'pll',
    'mcz', 'mcp', 'mvf', 'sao', 'mnx', 'nvt', 'gel', 'nat', 'oyk', 'poa', 'pbb',
    'poo', 'pfb', 'pmw', 'pet', 'pnz', 'pnb', 'pmg', 'bps', 'pvh', 'vdc', 'rbr',
    'rec', 'sdu', 'rao', 'brb', 'snz', 'sjk', 'slz', 'ria', 'stm', 'cgh', 'sjp',
    'ssz', 'ssa', 'qhp', 'tmt', 'una', 'tow', 'the', 'tff', 'trq', 'tec', 'obi',
    'tbt', 'tur', 'sjl', 'pav', 'urg', 'udi', 'uba', 'vag', 'bvh', 'vix', 'qps',
    'cpq', 'qcj', 'olc', 'sod', 'qdc', 'jls', 'qoa', 'qgc', 'qnv', 'ous', 'qhb',
    'qiq', 'qvp', 'qrz', 'qsc', 'ubt', 'qgs', 'vot', 'qgb', 'iza', 'lvr', 'frc',
    'cfo', 'jtc', 'ars', 'apy', 'apq', 'amj', 'aif', 'bdc', 'bvm', 'bra', 'bss',
    'bms', 'bqq', 'ctp', 'cpu', 'qch', 'rdc', 'lep', 'diq', 'cnv', 'sxx', 'odl',
    'gdp', 'gnm', 'gms', 'qgp', 'itn', 'ire', 'qig', 'qit', 'ipu', 'jcm', 'fec',
    'jeq', 'jna', 'jdr', 'cmp', 'qdf', 'qxd', 'qcp', 'lvb', 'sso', 'mte', 'mvs',
    'sbj', 'ptq', 'nnu', 'qbx', 'psw', 'orx', 'pcs', 'poj', 'piv', 'flb', 'jdo',
    'piv', 'pdf', 'cau', 'sfk', 'obi', 'tfl', 'val', 'qid', 'bvs', 'cmc', 'qxc',
    'phi', 'iti', 'ppy', 'apu', 'bnu', 'cci', 'qcn', 'cko', 'dou', 'erm', 'fbe',
    'qga', 'iju', 'itq', 'jcb', 'qdb', 'qcr', 'qre', 'alq', 'qmf', 'qgf', 'qhv',
    'sqx', 'apx', 'pto', 'png', 'pvi', 'pbb', 'qac', 'sqy', 'qoj', 'csu', 'umu',
    'qvb', 'via', 'ctq', 'axe', 'aag', 'sra', 'pgz', 'baz', 'rbb', 'caf', 'cqs',
    'dmt', 'dno', 'ars', 'ern', 'cqa', 'fej', 'sxo', 'grp', 'aux', 'ipg', 'ido',
    'jpr', 'jia', 'jrn', 'ccx', 'ciz', 'tlz', 'lbr', 'rvd', 'mbz', 'nvp', 'aqm',
    'bcr', 'nql', 'aps', 'pin', 'pmw', 'pbq', 'aai', 'roo', 'air', 'ops', 'stz',
    'irz', 'azl', 'qhn', 'sqm', 'vlp', 'mbk', 'nok', 'br-']],
  ['BS', ['nsb', 'may',
    'asd', 'cox', 'mhh', 'saq', 'axp', 'tcb', 'wkr', 'ccz', 'ghc', 'bim', 'atc',
    'cat', 'cxy', 'cri', 'pwn', 'ggt', 'elh', 'ghb', 'nmc', 'rsd', 'tym', 'fpo',
    'wtd', 'iga', 'lgi', 'sml', 'myg', 'nas', 'pid', 'dct', 'rcy', 'zsa']],
  ['BT',
    ['pbh']],
  ['BW', ['huk', 'frw', 'gnz', 'jwa', 'bbk', 'khw', 'mub', 'orp', 'qph',
    'gbe', 'sxn', 'pkw', 'swx', 'tld', 'tby']],
  ['BY', ['bqt', 'gme', 'vtb', 'gna',
    'mhp', 'msq', 'mvq']],
  ['BZ', ['bcv', 'bgk', 'cuk', 'cyc', 'czh', 'dga', 'inb',
    'mdb', 'orz', 'plj', 'pnd', 'sjx', 'spr', 'sqs', 'stu', 'svk', 'tza', 'bze']],
  ['CA', ['yuj', 'ywo', 'ytj', 'ymv', 'ybw', 'zna', 'yzz', 'yws', 'ypt', 'yaa',
    'jhl', 'ymu', 'ywm', 'yfx', 'yha', 'yrg', 'yck', 'ee7', 'yle', 'nml', 'das',
    'yfi', 'sur', 'yax', 'wnn', 'yno', 'xbe', 'kif', 'yog', 'yeb', 'yhp', 'ynx',
    'yku', 'ztb', 'yau', 'tr7', 'zlt', 'yac', 'yag', 'yah', 'yal', 'yam', 'xks',
    'ykg', 'yat', 'yav', 'yaw', 'yax', 'yay', 'yaz', 'ybb', 'ybc', 'qbc', 'ybe',
    'yby', 'ybg', 'ybk', 'ybl', 'ybn', 'xtl', 'ybr', 'ybt', 'ybv', 'ybx', 'yrf',
    'ycb', 'ycc', 'ycd', 'yce', 'ycg', 'ych', 'ycl', 'ycn', 'yco', 'ycq', 'ycr',
    'ycs', 'ycv', 'ycx', 'ycy', 'ycz', 'yda', 'ydb', 'ydf', 'ydm', 'ydn', 'ydo',
    'ydp', 'ydq', 'yed', 'yeg', 'yek', 'yel', 'yem', 'yen', 'yer', 'yet', 'yeu',
    'yev', 'yey', 'yfa', 'yfb', 'yfc', 'yfe', 'yfh', 'ytm', 'yfo', 'yfr', 'yfs',
    'ymn', 'ygb', 'ygd', 'ygh', 'ygk', 'ygl', 'ygm', 'ygo', 'ygp', 'ygq', 'ygr',
    'ygt', 'ygv', 'ygw', 'ygx', 'ygz', 'yqc', 'cxh', 'yhd', 'yhe', 'yhf', 'yns',
    'yhi', 'yhk', 'yhm', 'yhn', 'yho', 'yhr', 'yht', 'yhu', 'yhy', 'yhz', 'yib',
    'ydg', 'yif', 'yik', 'yio', 'yiv', 'yjf', 'yjn', 'yjt', 'yka', 'lak', 'ykf',
    'ykj', 'ykl', 'akv', 'ykq', 'ykx', 'yky', 'ykz', 'ypj', 'ylc', 'yld', 'ylh',
    'ylj', 'ysg', 'yll', 'ylr', 'ylt', 'xgr', 'ylw', 'yma', 'yme', 'ymg', 'ymh',
    'ymj', 'yml', 'ymm', 'ymo', 'ymt', 'yud', 'ymx', 'yna', 'ync', 'ynd', 'yne',
    'ynl', 'ynm', 'ynn', 'hzp', 'yoa', 'yoc', 'yod', 'yoh', 'yoj', 'yoo', 'yop',
    'yos', 'yow', 'yoy', 'ypa', 'ypc', 'yps', 'ype', 'ypg', 'yph', 'ypl', 'ypm',
    'ypn', 'ypo', 'ypq', 'ypr', 'ypw', 'ypx', 'ypy', 'yqa', 'yqb', 'yqd', 'yqf',
    'yqg', 'yqh', 'yqi', 'yqk', 'yql', 'yqm', 'yqn', 'yqq', 'yqr', 'yqs', 'yqt',
    'yqu', 'yqv', 'yqw', 'yqx', 'yqy', 'yqz', 'yra', 'yrb', 'yri', 'yrj', 'yrl',
    'yro', 'yrp', 'yrq', 'yrs', 'yrt', 'yrv', 'ysb', 'ysc', 'ysd', 'ysf', 'ysh',
    'ysj', 'ysk', 'ysl', 'ysm', 'ycm', 'ysp', 'ysr', 'yst', 'ysu', 'ysy', 'yta',
    'yte', 'ytf', 'yth', 'ytl', 'ytq', 'ytr', 'yts', 'ytz', 'yub', 'yul', 'yut',
    'yux', 'yuy', 'yvb', 'yvc', 'yvd', 'yve', 'yvm', 'yvo', 'yvp', 'yvq', 'yvr',
    'yvt', 'yvv', 'yvz', 'ywa', 'ywg', 'ywh', 'ywj', 'ywk', 'ywl', 'ywp', 'ywy',
    'yxc', 'yxd', 'yxe', 'yxh', 'yxi', 'yxj', 'yxk', 'yxl', 'yxn', 'yxp', 'yxq',
    'yxr', 'yxs', 'yxt', 'yxu', 'yxx', 'yxy', 'yxz', 'yyb', 'yyc', 'yyd', 'yye',
    'yyf', 'yyg', 'yyh', 'yyj', 'yyl', 'yyn', 'yyq', 'yyr', 'yyt', 'yyu', 'yyw',
    'yyy', 'yyz', 'yzd', 'yze', 'yzf', 'yzg', 'yzh', 'yzp', 'yzr', 'yzs', 'yzt',
    'yzu', 'yzv', 'yzw', 'yzx', 'yzy', 'zac', 'ysn', 'ydt', 'zbd', 'zbf', 'zbf',
    'zbm', 'zee', 'zem', 'zfa', 'zfd', 'zfg', 'zfm', 'zfn', 'zgf', 'zgi', 'zgr',
    'zjg', 'zjn', 'zke', 'ytd', 'msa', 'piw', 'zmt', 'zng', 'zpb', 'zrj', 'zsj',
    'zsn', 'zsw', 'ztm', 'zuc', 'zum', 'zwh', 'zwl', 'yoi', 'ytu']],
  ['CC',
    ['cck']],
  ['CD', ['fih', 'nlo', 'mnb', 'boa', 'lzi', 'mat', 'nkl', 'ino', 'nio',
    'fdu', 'krz', 'kkw', 'idf', 'lus', 'msm', 'mdk', 'bsu', 'lie', 'bdt', 'gma',
    'kli', 'bmb', 'liq', 'bnb', 'ikl', 'fki', 'yan', 'irp', 'bux', 'bzu', 'bky',
    'gom', 'bnc', 'knd', 'kly', 'pun', 'fbm', 'pwo', 'kec', 'kwz', 'mno', 'bdv',
    'fmi', 'kbo', 'koo', 'kmn', 'kap', 'knm', 'kga', 'lza', 'tsh', 'lja', 'lbo',
    'mew', 'ban', 'pfr', 'mjm', 'gdj', 'kbn']],
  ['CF', ['crf', 'bgf', 'bgu', 'iro',
    'bem', 'bby', 'ndl', 'bop', 'biv', 'bsn', 'bbt', 'oda', 'aig', 'imo', 'mki',
    'btg', 'gdi', 'bmf', 'odj', 'rfa', 'bcf', 'boz']],
  ['CG', ['okg', 'bzv', 'djm',
    'knj', 'lco', 'muy', 'sib', 'nky', 'anj', 'msx', 'boe', 'ewo', 'gmm', 'ion',
    'kee', 'mkj', 'ftx', 'soe', 'btb', 'oue', 'kmk', 'dis', 'pnr']],
  ['CH', ['gva',
    'qnc', 'sir', 'zin', 'lug', 'brn', 'bxo', 'aco', 'zhi', 'zrh', 'zji', 'ach',
    'smv']],
  ['CI', ['abj', 'ogo', 'bxi', 'byk', 'bqo', 'bdk', 'dim', 'djo', 'fek',
    'ggn', 'ggo', 'hgo', 'mjc', 'keo', 'ofi', 'seo', 'spy', 'zss', 'txu', 'ask']],
  ['CK', ['ait', 'aiu', 'mgs', 'mhx', 'muk', 'moi', 'pye', 'rar']],
  ['CL', ['zud',
    'lob', 'wap', 'ari', 'wpa', 'dat', 'bba', 'toq', 'cch', 'cjc', 'yai', 'puq',
    'gxq', 'iqq', 'scl', 'esr', 'frt', 'anf', 'wpr', 'ffu', 'lsq', 'wpu', 'cpo',
    'lgr', 'ccp', 'ipc', 'zos', 'vlr', 'zlr', 'pnt', 'ovl', 'zpc', 'pux', 'cnr',
    'vap', 'qrc', 'smb', 'lsc', 'ssd', 'wca', 'zco', 'pmc', 'ulc', 'tlx', 'wch',
    'zic', 'ttc', 'zal', 'kna']],
  ['CM', ['nks', 'kbi', 'tkc', 'dla', 'mmf', 'kle',
    'our', 'gxx', 'mvr', 'fom', 'nge', 'bta', 'gou', 'dsc', 'bfx', 'bpc', 'ebw',
    'yao', 'nsi']],
  ['CN', ['ohe', 'fuo', 'huz', 'jgs', 'aeb', 'aat', 'yzy', 'ddg',
    'ntg', 'dqa', 'hia', 'jgd', 'jic', 'jiq', 'lac', 'nbs', 'ohe', 'pek', 'cif',
    'cih', 'dsn', 'dat', 'erl', 'hdg', 'het', 'hld', 'nay', 'bav', 'shp', 'sjw',
    'tsn', 'tgo', 'hlh', 'xil', 'ycu', 'tyn', 'bhy', 'cgd', 'hjj', 'dyg', 'can',
    'csx', 'hny', 'kwl', 'mxz', 'nng', 'swa', 'zuh', 'szx', 'wuz', 'xin', 'lzh',
    'zha', 'ayn', 'cgo', 'enh', 'lhk', 'wuh', 'lya', 'nny', 'shs', 'xfn', 'yih',
    'hak', 'syx', 'aka', 'lhw', 'dnh', 'goq', 'gyu', 'hzg', 'inc', 'jng', 'jgn',
    'zgc', 'iqn', 'sia', 'xnn', 'xiy', 'eny', 'uyn', 'dlu', 'dig', 'jhg', 'ljg',
    'lum', 'kmg', 'sym', 'zat', 'xmn', 'aqg', 'czx', 'khn', 'foc', 'kow', 'hgh',
    'jdz', 'jiu', 'tna', 'juz', 'lcx', 'lyg', 'hyn', 'lyi', 'ngb', 'nkg', 'hfe',
    'pvg', 'tao', 'jjn', 'rug', 'sha', 'szv', 'txn', 'wef', 'weh', 'whu', 'wux',
    'wus', 'wnz', 'xuz', 'ynz', 'ynt', 'yiw', 'hsn', 'ngq', 'ava', 'bpx', 'ckg',
    'dax', 'gys', 'kwe', 'jzh', 'lia', 'lxa', 'lzo', 'mig', 'nao', 'lzy', 'tcz',
    'ctu', 'wxn', 'xic', 'ybp', 'acx', 'aku', 'bpl', 'iqm', 'hmi', 'kca', 'krl',
    'kry', 'khg', 'sxj', 'tcg', 'htn', 'urc', 'yin', 'aog', 'cgq', 'cni', 'chg',
    'hrb', 'hek', 'jil', 'jmu', 'jnz', 'yus', 'mdg', 'ohe', 'ndg', 'dlc', 'she',
    'ynj']],
  ['CO', ['prm', 'isg', 'api', 'apo', 'arq', 'lcr', 'snt', 'tcd', 'acm',
    'acl', 'nbb', 'azt', 'sqb', 'arf', 'acr', 'acd', 'afi', 'adn', 'apy', 'axm',
    'puu', 'elb', 'bga', 'bog', 'baq', 'bsc', 'bun', 'cpb', 'cuc', 'cog', 'ctg',
    'cco', 'clo', 'cim', 'rav', 'tco', 'cuo', 'caq', 'cve', 'czu', 'ebg', 'eja',
    'fla', 'fda', 'gir', 'crc', 'gpi', 'glj', 'cpl', 'htz', 'ibe', 'igo', 'mmp',
    'ipi', 'lqm', 'mcj', 'lpd', 'let', 'eoh', 'mfs', 'mgn', 'mcj', 'mtb', 'mtr',
    'mvp', 'mzl', 'nci', 'nqu', 'nva', 'ocv', 'orc', 'pcr', 'pda', 'pei', 'ptx',
    'plt', 'nar', 'ppn', 'pqe', 'pbe', 'pso', 'pva', 'pza', 'mqu', 'mde', 'rch',
    'sje', 'smr', 'sox', 'adz', 'svi', 'tbu', 'tda', 'tlu', 'tme', 'tqs', 'trb',
    'mqz', 'auc', 'uib', 'ulq', 'urr', 'vup', 'vvc', 'ayg', 'eyp']],
  ['CR', ['fon',
    'ttq', 'bai', 'bcl', 'csc', 'otr', 'rik', 'tno', 'fmg', 'glf', 'gpl', 'pbp',
    'lir', 'lsl', 'lio', 'nct', 'nom', 'sjo', 'pjm', 'pmz', 'syq', 'xqp', 'rfr',
    'pld', 'too', 'tno', 'tmu', 'upl']],
  ['CU', ['pst', 'bca', 'bww', 'bym', 'avi',
    'ccc', 'cfg', 'cyo', 'cmw', 'qco', 'scu', 'nbw', 'gao', 'hav', 'hog', 'vro',
    'lcl', 'uma', 'mjg', 'moa', 'mzo', 'qsn', 'icr', 'ger', 'upb', 'qpd', 'snu',
    'snj', 'szj', 'uss', 'tnd', 'vra', 'vtu']],
  ['CV', ['sid', 'nto', 'bvc', 'mmo',
    'mti', 'rai', 'sfl', 'sne', 'vxe']],
  ['CX', ['xch']],
  ['CY', ['gec', 'nic',
    'ecn', 'lca', 'pfo', 'akt']],
  ['CZ', ['gtw', 'uhe', 'klv', 'mka', 'osr', 'ped',
    'prv', 'prg', 'brq', 'zbe']],
  ['DE', ['aoc', 'hdf', 'bbh', 'zmg', 'cbu', 'sxf',
    'drs', 'erf', 'fra', 'fmo', 'ham', 'thf', 'cgn', 'dus', 'muc', 'nue', 'lej',
    'scn', 'str', 'txl', 'haj', 'bre', 'qef', 'hhn', 'mhg', 'zqv', 'qmz', 'sge',
    'xfw', 'kel', 'lbc', 'eum', 'fmm', 'aah', 'ess', 'bfe', 'mgl', 'pad', 'nrn',
    'dtm', 'agb', 'obf', 'rbm', 'fdh', 'frf', 'szw', 'byu', 'qob', 'hoq', 'bbj',
    'zqw', 'fkb', 'zql', 'lha', 'bwe', 'ksf', 'brv', 'xlw', 'eme', 'age', 'wvn',
    'jui', 'lgo', 'zow', 'bmk', 'nod', 'vac', 'nrd', 'bmr', 'hei', 'flf', 'hgl',
    'psh', 'gwt', 'ohr', 'spm', 'rms', 'zcd', 'zcn', 'zpq', 'frz', 'znf', 'qhd',
    'ndz', 'gke', 'rlg', 'qoe', 'wbg', 'fnb', 'wie', 'fel', 'igs', 'gut', 'bgn',
    'edg', 'muc']],
  ['DJ', ['jib', 'aii', 'mhi', 'obc', 'tdj']],
  ['DK', ['aar',
    'bll', 'cph', 'ebj', 'krp', 'byr', 'mrw', 'ode', 'rke', 'rnn', 'sgd', 'cnl',
    'sks', 'sqw', 'ted', 'vdp', 'sta', 'aal']],
  ['DM', ['dcf', 'dom']],
  ['DO',
    ['sti', 'eps', 'brx', 'cbj', 'azs', 'coz', 'hex', 'jbq', 'lrm', 'puj', 'pop',
      'snx', 'sdq', 'sjm', 'sti']],
  ['DZ', ['qld', 'buj', 'bja', 'alg', 'djg', 'qfd',
    'vvz', 'qsf', 'tmr', 'gjl', 'mzw', 'qzn', 'aae', 'czl', 'tee', 'blj', 'hrm',
    'tid', 'tin', 'qas', 'taf', 'tlm', 'orn', 'cbh', 'muw', 'ebh', 'inf', 'bmw',
    'azr', 'bsk', 'elg', 'gha', 'hme', 'inz', 'tgr', 'loo', 'elu', 'tmx', 'ogx',
    'iam']],
  ['EC', ['mzd', 'atf', 'occ', 'cue', 'gps', 'gye', 'ibb', 'jip', 'ltx',
    'mrr', 'xms', 'mch', 'mec', 'lgq', 'pyo', 'pvo', 'uio', 'etr', 'snc', 'suq',
    'ptz', 'scy', 'bha', 'tsc', 'tpn', 'loh', 'esm', 'tpc', 'tua']],
  ['EE', ['kdl',
    'ure', 'epu', 'tll', 'tay']],
  ['EG', ['aue', 'sew', 'dbb', 'aac', 'atz', 'aly',
    'hbe', 'abs', 'cai', 'cwe', 'dak', 'hrg', 'egh', 'uvl', 'lxr', 'rmf', 'hmb',
    'muh', 'gsq', 'psd', 'skv', 'ssh', 'asw', 'tcp', 'elt']],
  ['EH', ['smw', 'vil',
    'eun']],
  ['ER', ['asm', 'msw', 'asa', 'tes']],
  ['ES', ['aei', 'fue', 'gmz',
    'vde', 'spc', 'lpa', 'ace', 'tfs', 'tfn', 'jcu', 'mln', 'abc', 'alc', 'lei',
    'ovd', 'odb', 'bio', 'rgs', 'bcn', 'bjz', 'cdt', 'lcg', 'gro', 'grx', 'ccx',
    'ibz', 'xry', 'mjv', 'qsa', 'len', 'rjl', 'mad', 'hev', 'agp', 'mah', 'ozp',
    'pmi', 'pna', 'cqm', 'reu', 'slm', 'eas', 'scq', 'leu', 'toj', 'vlc', 'vll',
    'vit', 'vgo', 'sdr', 'zaz', 'svq']],
  ['ET', ['glc', 'shc', 'add', 'amh', 'axu',
    'bco', 'bjr', 'bei', 'dse', 'dem', 'dbm', 'dir', 'dbt', 'fnh', 'gob', 'gnn',
    'gmb', 'gdq', 'gde', 'gor', 'qhr', 'hue', 'jim', 'abk', 'lfo', 'awa', 'lli',
    'mqx', 'ndm', 'mtf', 'nej', 'nek', 'sxu', 'aso', 'tie', 'wac', 'hil']],
  ['FI',
    ['enf', 'qve', 'kev', 'hem', 'hel', 'hyv', 'ktq', 'ivl', 'joe', 'jyv', 'kau',
      'kem', 'kaj', 'khj', 'kok', 'kao', 'ktt', 'kuo', 'qlf', 'lpp', 'mhq', 'mik',
      'oul', 'por', 'rvn', 'svl', 'sjy', 'sot', 'tmp', 'tku', 'uti', 'vaa', 'vrk',
      'yli']],
  ['FJ', ['ici', 'nan', 'ptf', 'kdv', 'mnf', 'mfj', 'suv', 'lev', 'ngi',
    'luc', 'lkb', 'lbs', 'tvu', 'kxf', 'rta', 'svu', 'vau', 'kay', 'onu', 'yas',
    'vbv', 'vtf']],
  ['FK', ['mpn', 'psy']],
  ['FM', ['uli', 'tkk', 'pni', 'ksa',
    'yap']],
  ['FO', ['fae']],
  ['FR', ['jca', 'dpe', 'cqf', 'xcp', 'xln', 'xsj',
    'xdk', 'byf', 'ltq', 'xvs', 'qam', 'agf', 'bod', 'egc', 'cng', 'lrh', 'pis',
    'mcu', 'lig', 'xmj', 'nit', 'tls', 'puf', 'lde', 'ang', 'bve', 'pgx', 'xda',
    'biq', 'xcx', 'zao', 'xgt', 'xac', 'lbi', 'dcm', 'rdz', 'ryn', 'xmw', 'xlr',
    'rco', 'xsl', 'xtb', 'idy', 'cmr', 'xbv', 'dle', 'xvn', 'mvv', 'obs', 'lpy',
    'ahz', 'etz', 'ane', 'bia', 'cly', 'fsc', 'aja', 'prp', 'soz', 'mfx', 'auf',
    'cmf', 'cfe', 'bou', 'qnj', 'cvf', 'lys', 'qnx', 'syt', 'rne', 'ncy', 'xmk',
    'gnb', 'mcu', 'vaf', 'vhy', 'aur', 'chr', 'lyn', 'ceq', 'ebu', 'qie', 'ccf',
    'mrs', 'nce', 'xog', 'pgf', 'ctt', 'bae', 'xas', 'mpl', 'bzr', 'avn', 'gat',
    'men', 'scp', 'bva', 'xsu', 'evx', 'xan', 'leh', 'xab', 'ore', 'xcr', 'lso',
    'uro', 'xbq', 'qtj', 'tuf', 'cet', 'lva', 'lbg', 'csf', 'cdg', 'jdp', 'tnf',
    'ory', 'pox', 'viy', 'qyr', 'nvs', 'xcb', 'xme', 'lil', 'hzb', 'xcz', 'xvo',
    'bes', 'cer', 'dnr', 'lby', 'gfr', 'dol', 'lrt', 'edm', 'ldv', 'cfr', 'lme',
    'rns', 'lai', 'uip', 'nte', 'sbk', 'mxn', 'vne', 'snr', 'qbq', 'bsl', 'dij',
    'mzm', 'epl', 'xmf', 'enc', 'bor', 'rhe', 'sxb', 'vtl', 'xhe', 'fni', 'ltt']],
  ['GA', ['bgb', 'kdn', 'fou', 'mbc', 'mgx', 'kdj', 'kou', 'mjl', 'oye', 'okn',
    'lbq', 'mvx', 'bmm', 'mff', 'mkb', 'pog', 'omb', 'mku', 'lbv', 'mzc', 'mvb',
    'ltl', 'zkm', 'tch', 'myb', 'ake', 'gax']],
  ['GB', ['bfs', 'enk', 'bhd', 'ldy',
    'bhx', 'cvt', 'glo', 'orm', 'nqt', 'man', 'xxb', 'dsa', 'lye', 'dgx', 'yeo',
    'cal', 'eoi', 'fie', 'whs', 'col', 'nrl', 'obn', 'ppw', 'soy', 'ndy', 'lwk',
    'wry', 'csa', 'haw', 'cwl', 'sws', 'brs', 'lpl', 'ltn', 'leq', 'plh', 'isc',
    'boh', 'sou', 'bbp', 'pze', 'qla', 'nqy', 'qug', 'esh', 'bqh', 'lgw', 'krh',
    'lcy', 'fab', 'bbs', 'lhr', 'sen', 'lyx', 'mse', 'cax', 'blk', 'huy', 'bwf',
    'lba', 'ceg', 'ncl', 'mme', 'ema', 'hly', 'koi', 'lsi', 'wic', 'abz', 'inv',
    'gla', 'edi', 'ily', 'pik', 'beb', 'scs', 'dnd', 'syy', 'brr', 'psl', 'tre',
    'unt', 'bol', 'fss', 'adx', 'lmo', 'cbg', 'nwi', 'stn', 'qfo', 'sze', 'ext',
    'frk', 'fzo', 'oxf', 'rcs', 'bex', 'lkz', 'mhz', 'quy', 'ffd', 'bzz', 'odh',
    'wxf', 'adv', 'nht', 'gsy', 'qcy', 'beq', 'okh', 'sqz', 'hrt', 'wtn', 'mrh',
    'fea', 'doc', 'flh', 'foa', 'ouk', 'psv', 'ull', 'skl']],
  ['GD', ['gnd',
    'cru']],
  ['GE', ['kut', 'bus', 'sui', 'tbs']],
  ['GF', ['cay', 'mpy', 'oxp',
    'ldx', 'rei', 'xau']],
  ['GG', ['aci', 'gci']],
  ['GH', ['acc', 'tml', 'kms',
    'nyi', 'tkd']],
  ['GI', ['gib']],
  ['GL', ['jeg', 'aap', 'agm', 'llu', 'quv',
    'quw', 'qgq', 'uak', 'jch', 'cnp', 'qfg', 'qfn', 'jfr', 'goh', 'jgo', 'ike',
    'qfi', 'xiq', 'inn', 'iso', 'qji', 'jju', 'jav', 'qpw', 'kus', 'upk', 'kmt',
    'klq', 'kaq', 'qje', 'ill', 'mor', 'jsu', 'qmk', 'jnn', 'nug', 'jns', 'nia',
    'nus', 'jfr', 'qqt', 'naq', 'oby', 'sfj', 'smg', 'sio', 'qup', 'jhs', 'saa',
    'sav', 'thu', 'tnt', 'juv', 'umd', 'jqa', 'ukk', 'jgr', 'qcu', 'qfx']],
  ['GM',
    ['bjl']],
  ['GN', ['cky', 'fig', 'faa', 'ksi', 'lek', 'mca', 'nze', 'bkj', 'sbi',
    'gii', 'knn']],
  ['GP', ['dsd', 'bbr', 'sfc', 'gbj', 'ptp', 'lss']],
  ['GQ',
    ['bsg', 'ssg']],
  ['GR', ['jss', 'pyr', 'agq', 'axd', 'hew', 'ath', 'vol', 'jkh',
    'pkh', 'jik', 'ioa', 'her', 'kso', 'kit', 'efl', 'kzs', 'klx', 'kgs', 'aok',
    'cfu', 'ksj', 'kva', 'kzi', 'lrs', 'lxs', 'lra', 'jmk', 'mlo', 'mjt', 'jnx',
    'pas', 'jty', 'pvk', 'rho', 'gpa', 'chq', 'jsi', 'smi', 'jsy', 'spj', 'jtr',
    'jsh', 'sku', 'skg', 'zth']],
  ['GT', ['ciq', 'don', 'enj', 'pcg', 'lcf', 'tkm',
    'uax', 'pkj', 'cbv', 'cmm', 'ctf', 'gua', 'hug', 'mcr', 'pbr', 'pon', 'aqb',
    'aaz', 'ruv', 'rer', 'gsj', 'frs']],
  ['GU', ['uam', 'gum']],
  ['GW', ['bqe',
    'oxb']],
  ['GY', ['bcg', 'kia', 'ahl', 'nai', 'bmj', 'gfo', 'geo', 'ogl', 'imb',
    'kar', 'krm', 'krg', 'kto', 'lub', 'ltm', 'usi', 'mha', 'mym', 'qsx', 'orj',
    'prr']],
  ['HK', ['hkg', 'hkg', 'hhp']],
  ['HN', ['ahs', 'bhg', 'caa', 'cdd',
    'jut', 'lce', 'lez', 'sap', 'gja', 'peu', 'rtb', 'sdh', 'ruy', 'xpl', 'tea',
    'tgu', 'tji', 'scd', 'uii']],
  ['HR', ['dbv', 'lsz', 'osi', 'puy', 'rjk', 'bwk',
    'spu', 'zag', 'zad']],
  ['HT', ['cya', 'cap', 'jak', 'jee', 'pap', 'pax']],
  ['HU', ['bud', 'deb', 'mcq', 'pev', 'qgy', 'sob', 'tzr', 'qzd']],
  ['ID', ['ppj',
    'aas', 'agd', 'akq', 'ayw', 'bjg', 'bxm', 'drh', 'elr', 'ewe', 'foo', 'gav',
    'iul', 'kbf', 'kbx', 'kcd', 'kea', 'kmm', 'kod', 'krc', 'kwb', 'lln', 'lwe',
    'lyk', 'mjy', 'mpt', 'msi', 'muf', 'naf', 'nda', 'obd', 'ppj', 'pum', 'pwl',
    'raq', 'rki', 'rti', 'ruf', 'rzs', 'sae', 'tbm', 'tmy', 'zeg', 'zgp', 'kmm',
    'upg', 'mju', 'bik', 'oni', 'wet', 'nbx', 'ila', 'kox', 'zri', 'tim', 'ewi',
    'ami', 'bmu', 'dps', 'lop', 'swq', 'tmc', 'wgp', 'arj', 'bui', 'zrm', 'djj',
    'lhi', 'lii', 'okl', 'war', 'seh', 'ubr', 'wmx', 'mdp', 'bxd', 'mkq', 'okq',
    'kei', 'tmh', 'tjs', 'dtd', 'bej', 'bpn', 'trk', 'sri', 'tsx', 'byq', 'glx',
    'gto', 'nah', 'tli', 'geb', 'kaz', 'plw', 'mdc', 'mna', 'psj', 'oti', 'tte',
    'luw', 'uol', 'btw', 'pkn', 'kbu', 'mtw', 'tjg', 'bdj', 'pky', 'smq', 'ahi',
    'dob', 'mal', 'nre', 'lah', 'sxk', 'bjk', 'luv', 'sqn', 'amq', 'nam', 'tax',
    'mlg', 'cpf', 'jog', 'soc', 'sub', 'srg', 'sup', 'nti', 'rsk', 'keq', 'fkq',
    'inx', 'kng', 'rde', 'bxb', 'mkw', 'soq', 'txm', 'wsr', 'bjw', 'mof', 'ene',
    'rtg', 'ard', 'lbj', 'koe', 'buw', 'mxb', 'sqr', 'ttr', 'kdi', 'tkg', 'pku',
    'dum', 'rko', 'seq', 'tjb', 'bdo', 'cbn', 'tsy', 'bth', 'ppr', 'tnj', 'siq',
    'hlp', 'cxp', 'pcb', 'cgk', 'llg', 'gns', 'aeg', 'pdg', 'mes', 'tjq', 'npo',
    'ktg', 'mwk', 'ntx', 'pnk', 'psu', 'sqg', 'djb', 'pgk', 'bks', 'plm', 'pdo',
    'rgt', 'pdg', 'mpc', 'klq', 'tpk', 'sbg', 'meq', 'lsx', 'lsw', 'btj', 'abu',
    'bjw', 'lka', 'sau', 'sgq', 'lbw', 'bxt', 'nnx', 'tnb', 'lpu', 'szh']],
  ['IE',
    ['byt', 'bly', 'nnr', 'clb', 'wex', 'ork', 'gwy', 'cfn', 'dub', 'ior', 'inq',
      'kky', 'noc', 'kir', 'ltr', 'iia', 'snn', 'sxl', 'wat', 'ior', 'che']],
  ['IL',
    ['tlv', 'bev', 'eth', 'eiy', 'hfa', 'rpn', 'ksw', 'mtz', 'vtm', 'vda', 'mip',
      'sdv', 'yot']],
  ['IM', ['iom']],
  ['IN', ['vdy', 'jgb', 'nvy', 'rji', 'tei',
    'diu', 'amd', 'akd', 'ixu', 'bom', 'pab', 'bhj', 'ixg', 'bdq', 'bho', 'bhu',
    'nmb', 'gux', 'goi', 'hbx', 'idr', 'jlr', 'jga', 'ixy', 'hjr', 'klh', 'ixk',
    'ndc', 'nag', 'isk', 'pnq', 'pbd', 'rtc', 'raj', 'rpr', 'sse', 'stv', 'udr',
    'ixv', 'ixa', 'ajl', 'ixb', 'rgh', 'shl', 'bbi', 'ccu', 'coh', 'dbd', 'dae',
    'gop', 'gau', 'gay', 'imf', 'pyb', 'ixw', 'jrh', 'ixq', 'ixh', 'ixs', 'ixn',
    'ajl', 'ixi', 'lda', 'dib', 'dmu', 'mzu', 'ixt', 'pat', 'ixr', 'rrk', 'rup',
    'tez', 'vtz', 'zer', 'agr', 'ixd', 'atq', 'bkb', 'vns', 'kuu', 'bup', 'ixc',
    'ded', 'del', 'dhm', 'gwl', 'hss', 'jdh', 'jai', 'jsa', 'ixj', 'knu', 'ktu',
    'luh', 'ixl', 'lko', 'ixp', 'pgh', 'slv', 'sxr', 'tni', 'ltu', 'agx', 'bep',
    'blr', 'vga', 'cjb', 'cok', 'ccj', 'cdp', 'cbd', 'hyd', 'ixm', 'ixe', 'maa',
    'myq', 'ixz', 'pny', 'hyd', 'rja', 'sxv', 'tjv', 'tir', 'trz', 'trv', 'wgc']],
  ['IO', ['nkw']],
  ['IQ', ['iqa', 'bmn', 'sda', 'osb', 'ebl', 'kik', 'bsr',
    'oso']],
  ['IR', ['kha', 'gsm', 'abd', 'omi', 'mrx', 'awz', 'aeu', 'buz', 'aoy',
    'knr', 'kih', 'bdh', 'yeh', 'khk', 'sxi', 'lvp', 'ksh', 'iil', 'khd', 'sdg',
    'ifh', 'ifn', 'cqd', 'ras', 'hdm', 'ajk', 'ika', 'thr', 'bnd', 'ker', 'bxr',
    'hdr', 'rjn', 'syj', 'xbj', 'ckt', 'mhd', 'bjb', 'afz', 'tcx', 'bbl', 'gbt',
    'bsm', 'nsh', 'rzr', 'sry', 'faz', 'lrr', 'syz', 'khy', 'adu', 'acp', 'pfq',
    'omh', 'tbz', 'azd', 'acz', 'zbr', 'zah']],
  ['IS', ['aey', 'biu', 'bgj', 'bjd',
    'blo', 'bqd', 'bxv', 'dju', 'egs', 'fas', 'fag', 'guu', 'gjr', 'gry', 'hvk',
    'hfn', 'fli', 'hzk', 'hvm', 'hlo', 'ifj', 'kef', 'opa', 'sak', 'nor', 'ofj',
    'pfj', 'rha', 'oli', 'rfn', 'rek', 'mva', 'sij', 'syk', 'tey', 'tho', 'tho',
    'vey', 'vpn']],
  ['IT', ['tqr', 'crv', 'bri', 'fog', 'tar', 'lcc', 'psr', 'bds',
    'suf', 'ciy', 'cta', 'lmp', 'pnl', 'pmo', 'reg', 'tps', 'nsy', 'blx', 'ran',
    'zia', 'aho', 'dci', 'cag', 'olb', 'ttb', 'qva', 'qmm', 'mxp', 'bgy', 'trn',
    'all', 'goa', 'lin', 'pmf', 'qpz', 'aot', 'cuf', 'avb', 'bzo', 'udn', 'blq',
    'tsf', 'frl', 'vbs', 'trs', 'rmi', 'vic', 'qpa', 'vrn', 'aoi', 'vce', 'qzo',
    'lcv', 'qrt', 'say', 'cia', 'fco', 'qfr', 'qsr', 'eba', 'qlt', 'nap', 'psa',
    'flr', 'grs', 'peg']],
  ['JE', ['jer']],
  ['JM', ['ocj', 'kin', 'mbj', 'pot',
    'neg', 'ktp']],
  ['JO', ['amm', 'adj', 'aqj', 'omf']],
  ['JP', ['nrt', 'mmj',
    'ibr', 'mus', 'iwo', 'kix', 'shm', 'ukb', 'hiw', 'tjh', 'obo', 'cts', 'hkd',
    'kuh', 'mmb', 'shb', 'okd', 'rbj', 'wkj', 'iki', 'ubj', 'tsj', 'mbe', 'akj',
    'oir', 'ris', 'kum', 'fuj', 'fuk', 'tne', 'koj', 'kmi', 'oit', 'kkj', 'hsg',
    'kmj', 'ngs', 'ngo', 'asj', 'oke', 'kkx', 'tkn', 'nkm', 'fkj', 'qgu', 'kmq',
    'oki', 'toy', 'ntq', 'hij', 'okj', 'izo', 'ygj', 'kcz', 'myj', 'itm', 'ttj',
    'tks', 'tak', 'iwj', 'aoj', 'gaj', 'sds', 'fks', 'hhe', 'hna', 'axt', 'msj',
    'kij', 'onj', 'sdj', 'syo', 'nja', 'hac', 'oim', 'mye', 'hnd', 'qut', 'oko',
    'oka', 'dna', 'isg', 'ueo', 'kjp', 'mmd', 'mmy', 'agj', 'iej', 'htr', 'ktd',
    'shi', 'tra', 'rnj', 'ogn']],
  ['KE', ['bmq', 'asv', 'edl', 'eys', 'klk', 'gas',
    'hoa', 'nbo', 'ggm', 'kis', 'ilu', 'key', 'ktl', 'lkg', 'lok', 'lau', 'loy',
    'nde', 'rbt', 'myd', 'mba', 'mre', 'oyl', 'nye', 'nuu', 'wil', 'nyk', 'uas',
    'uka', 'wjr', 'jjm', 'vpg', 'krv', 'kiu', 'lbk', 'lbn', 'lku', 'mre', 'mum',
    'kwy']],
  ['KG', ['fru', 'oss']],
  ['KH', ['bbm', 'kzc', 'kkz', 'kti', 'pnh',
    'rbe', 'rep', 'tnx', 'kos']],
  ['KI', ['abf', 'bez', 'kuc', 'mnk', 'mzk', 'mtk',
    'nig', 'oot', 'trw', 'aea', 'tbf', 'tmn', 'non', 'ais', 'tsu', 'bbg', 'aak',
    'cis', 'cxi', 'tnv']],
  ['KM', ['hah', 'nwa', 'yva', 'ajn']],
  ['KN', ['skb',
    'nev']],
  ['KP', ['dso', 'fnj']],
  ['KR', ['kwj', 'kuv', 'mpk', 'chn', 'rsu',
    'qun', 'sho', 'kag', 'wju', 'yny', 'cju', 'chf', 'pus', 'hin', 'usn', 'icn',
    'ssn', 'osn', 'gmp', 'swu', 'kpo', 'tae', 'cjj', 'yec', 'ujn']],
  ['KS', ['prn',
    'gja']],
  ['KW', ['kwi']],
  ['KY', ['cyb', 'lyb', 'gcm']],
  ['KZ', ['dzn', 'tdk',
    'atx', 'ala', 'bxh', 'bxj', 'tse', 'kov', 'ppk', 'dmb', 'cit', 'dzn', 'kgf',
    'kzo', 'ura', 'ekb', 'ukk', 'pwq', 'dlx', 'sco', 'guw', 'akx', 'ayk', 'ksn']],
  ['LA', ['pcq', 'aou', 'oui', 'lpq', 'lxg', 'ody', 'pkz', 'zby', 'zvk', 'neu',
    'vna', 'thk', 'vte', 'xkh']],
  ['LB', ['bey', 'kye']],
  ['LC', ['slu', 'uvf']],
  ['LK', ['ayy', 'byv', 'pqd', 'cmb', 'acj', 'btc', 'rml', 'goy', 'mnh', 'jaf',
    'kct', 'giu', 'trr', 'wrz']],
  ['LR', ['ucn', 'cpa', 'sni', 'ucn', 'mlw', 'nia',
    'rob', 'saz', 'thc', 'voi']],
  ['LS', ['lef', 'lrb', 'les', 'mfc', 'mkh', 'msu',
    'nku', 'pel', 'utg', 'une', 'shk', 'skq', 'sok', 'shz', 'thb', 'tko']],
  ['LT',
    ['kun', 'klj', 'plq', 'pnv', 'sqq', 'hlj', 'vno']],
  ['LU', ['lux']],
  ['LV',
    ['lpx', 'rix', 'vnt']],
  ['LY', ['srx', 'tob', 'ght', 'akf', 'ben', 'mji', 'laq',
    'seb', 'tip', 'lmq', 'huq', 'ltd', 'wax', 'bcq', 'dnf', 'mra', 'qub']],
  ['MA',
    ['aga', 'tta', 'ozg', 'uar', 'fez', 'erh', 'mek', 'oud', 'gmd', 'cas', 'rba',
      'sii', 'esu', 'cmn', 'sfi', 'ndr', 'rak', 'nna', 'ozz', 'ahu', 'ttu', 'tng',
      'gln']],
  ['MD', ['bzy', 'kiv']],
  ['ME', ['ivg', 'tgd', 'tiv', 'zbk']],
  ['MF',
    ['sfg']],
  ['MG', ['ahy', 'amy', 'wml', 'atj', 'waq', 'vvb', 'tnr', 'jva', 'bmd',
    'zva', 'mxt', 'ilk', 'tva', 'sms', 'tmm', 'wta', 'moq', 'wts', 'vat', 'wam',
    'die', 'wmr', 'zwa', 'amb', 'wbd', 'wpb', 'anm', 'iva', 'hva', 'mjn', 'nos',
    'dwb', 'wmp', 'bpy', 'wmn', 'svb', 'tts', 'voh', 'wai', 'wma', 'wbo', 'wmd',
    'ftu', 'wfi', 'rva', 'iho', 'mja', 'wvk', 'ova', 'mnj', 'tdv', 'mxm', 'tle',
    'bku', 'amp', 'wak', 'doa']],
  ['MH', ['utk', 'aip', 'aim', 'aul', 'bii', 'ebn',
    'jat', 'jej', 'kbt', 'lik', 'lml', 'mav', 'mjb', 'mje', 'ndk', 'rnp', 'tic',
    'uit', 'wja', 'wte', 'wto', 'mij', 'ent', 'maj', 'kwa', 'kio', 'uje']],
  ['MK',
    ['ohd', 'skp']],
  ['ML', ['bko', 'gud', 'gaq', 'knz', 'ktx', 'kys', 'mzi', 'nrm',
    'nix', 'kss', 'tom', 'eyl']],
  ['MM', ['heb', 'nyu', 'bmo', 'tvy', 'nyt', 'gaw',
    'gwa', 'heh', 'hox', 'tio', 'ket', 'khm', 'kmv', 'kyp', 'kaw', 'kyt', 'liw',
    'lsh', 'mdl', 'mgz', 'myt', 'mnu', 'mgu', 'moe', 'mog', 'mgk', 'mwq', 'nms',
    'nmt', 'paa', 'pau', 'bsx', 'ppu', 'pbu', 'pkk', 'pru', 'aky', 'snw', 'thl',
    'xye', 'rgn']],
  ['MN', ['mxw', 'ulg', 'ulz', 'avk', 'lti', 'byn', 'uga', 'ugt',
    'hbu', 'uun', 'coq', 'dlz', 'hvd', 'mxv', 'uln', 'ulg']],
  ['MO', ['mfm']],
  ['MP', ['rop', 'spn', 'tiq']],
  ['MQ', ['fdf']],
  ['MR', ['aeo', 'otl', 'thi',
    'tiy', 'bgh', 'kfa', 'tmd', 'emn', 'ajj', 'ked', 'mom', 'nkc', 'sey', 'tht',
    'atr', 'fgd', 'ndb', 'ouz']],
  ['MS', ['mni', 'mni']],
  ['MT', ['gzm', 'mla']],
  ['MU', ['mru', 'rrg']],
  ['MV', ['fvm', 'gan', 'haq', 'kdo', 'mle', 'kdm',
    'vam']],
  ['MW', ['ceh', 'blz', 'cmk', 'dwa', 'kgj', 'kbq', 'llw', 'lix', 'mai',
    'myz', 'lmb', 'zzu', 'vuu']],
  ['MX', ['amc', 'bhl', 'blm', 'aca', 'ntr', 'agu',
    'hux', 'cna', 'cvj', 'acn', 'cme', 'ncg', 'cul', 'ctm', 'cen', 'cjt', 'cpe',
    'cjs', 'cza', 'cuu', 'cvm', 'cyw', 'czm', 'cua', 'mmc', 'dgo', 'tpq', 'ese',
    'gdl', 'gym', 'gub', 'tcn', 'hmo', 'clq', 'isj', 'slw', 'izt', 'jal', 'azp',
    'lzc', 'lmm', 'bjx', 'lap', 'lto', 'mam', 'mid', 'mug', 'mxl', 'mlm', 'mtt',
    'lov', 'mex', 'mty', 'mzt', 'nog', 'nld', 'oax', 'paz', 'pbc', 'ppe', 'pds',
    'upn', 'pqm', 'pvr', 'pxm', 'qro', 'rex', 'szt', 'sjd', 'sfh', 'slp', 'tgm',
    'trc', 'tij', 'tam', 'tsl', 'tlc', 'tap', 'wix', 'cun', 'vsa', 'ver', 'zcl',
    'zih', 'zmm', 'zlo', 'ajs', 'azg', 'ceo', 'nvj', 'pcm', 'pcv', 'pno', 'scx',
    'sgm', 'tuy', 'uac', 'xal']],
  ['MY', ['gtb', 'gtk', 'lbp', 'llm', 'mzs', 'spt',
    'btu', 'blg', 'lsm', 'lgl', 'kch', 'odn', 'lmn', 'mkm', 'lkh', 'mur', 'bse',
    'kpi', 'bkm', 'myy', 'sbw', 'tgc', 'lsu', 'lwy', 'sgg', 'bbn', 'smm', 'ldu',
    'tel', 'kgu', 'sxs', 'bki', 'lbu', 'tmg', 'gsa', 'spe', 'pay', 'rnu', 'sdk',
    'kud', 'twu', 'mzv', 'sxt', 'mep', 'swy', 'tpg', 'tod', 'aor', 'bwh', 'kbr',
    'kua', 'kte', 'iph', 'jhb', 'kul', 'lgk', 'mkz', 'tgg', 'pen', 'pkg', 'rdn',
    'szb']],
  ['MZ', ['ame', 'bcw', 'bzb', 'ano', 'bew', 'fxo', 'vpy', 'ihc', 'inh',
    'vxc', 'mpm', 'mud', 'mzb', 'mnc', 'apl', 'pol', 'uel', 'tet', 'vnx', 'vjb',
    'ibl', 'mtu', 'mfw', 'tgs']],
  ['NA', ['adi', 'gog', 'gfy', 'mpa', 'kmp', 'lud',
    'oku', 'nni', 'ond', 'omg', 'omd', 'okf', 'ndu', 'swp', 'tsb', 'wvb', 'ers',
    'wdh']],
  ['NC', ['tgj', 'bmy', 'knq', 'ilp', 'hlu', 'koc', 'lif', 'gea', 'iou',
    'puv', 'pdc', 'mee', 'tou', 'uve', 'nou']],
  ['NE', ['mfq', 'nim', 'thz', 'ajy',
    'znd']],
  ['NF', ['nlk']],
  ['NG', ['dka', 'abv', 'akr', 'abb', 'bni', 'cbq',
    'enu', 'qus', 'iba', 'ilr', 'qow', 'jos', 'kad', 'kan', 'miu', 'mdi', 'los',
    'mxj', 'phc', 'sko', 'yol', 'zar', 'gmo', 'phg', 'bcu', 'qrw', 'phg']],
  ['NI',
    ['bef', 'bza', 'rni', 'mga', 'nvg', 'puz', 'rfs', 'ncr', 'siu', 'wsp']],
  ['NL',
    ['ams', 'mst', 'qar', 'ein', 'grq', 'glz', 'dhr', 'ley', 'lwr', 'rtm', 'utc',
      'ens', 'lid', 'ude', 'woe']],
  ['NO', ['aes', 'anx', 'alf', 'fde', 'bnn', 'boo',
    'bgo', 'bjf', 'bvg', 'krs', 'dld', 'bdu', 'eve', 'fbu', 'vdb', 'fro', 'osl',
    'hmr', 'hau', 'hft', 'haa', 'hvg', 'qkx', 'ksu', 'gll', 'kkn', 'fan', 'lkn',
    'meh', 'mol', 'mjf', 'lkl', 'nvk', 'osy', 'ntb', 'ola', 'hov', 'mqn', 'rvk',
    'rrs', 'ret', 'ryg', 'lyr', 'sdn', 'sog', 'svj', 'skn', 'ske', 'srp', 'soj',
    'vaw', 'ssj', 'tos', 'trf', 'trd', 'vds', 'vry', 'svg']],
  ['NP', ['mwp', 'tpj',
    'bjh', 'bhp', 'bgl', 'bhr', 'bju', 'bit', 'bwa', 'bdp', 'dnp', 'dhi', 'dap',
    'dop', 'sih', 'gkh', 'jir', 'jum', 'jkr', 'ktm', 'ldn', 'lua', 'ltg', 'ngx',
    'mey', 'xmg', 'kep', 'pkr', 'ppl', 'rjb', 'rhp', 'ruk', 'rum', 'sif', 'skh',
    'feb', 'imk', 'tmi', 'bir']],
  ['NR', ['inu']],
  ['NU', ['iue']],
  ['NZ', ['akl',
    'tuo', 'amz', 'asg', 'chc', 'cht', 'cmv', 'dgr', 'dud', 'fgl', 'who', 'gbz',
    'gmn', 'gis', 'gtn', 'hkk', 'hlz', 'wik', 'kbz', 'kke', 'kko', 'kat', 'alr',
    'mta', 'mon', 'mfn', 'mzp', 'teu', 'mro', 'npl', 'npe', 'nsn', 'ivc', 'oha',
    'oam', 'pmr', 'pcn', 'ppq', 'zqn', 'rag', 'szs', 'rot', 'trg', 'tmz', 'ktf',
    'tkz', 'thh', 'tiu', 'twz', 'bhe', 'wka', 'whk', 'wlg', 'wir', 'wre', 'wsz',
    'wtz', 'wag']],
  ['OM', ['bjq', 'byb', 'aom', 'rmb', 'khs', 'msh', 'mct', 'omm',
    'sll', 'suh', 'tth', 'ukh']],
  ['PA', ['boc', 'ctd', 'chx', 'dav', 'onx', 'blb',
    'jqe', 'plp', 'pac', 'syp', 'pty', 'nbl', 'acu', 'ail', 'aml', 'bfq', 'ele',
    'otd', 'sax']],
  ['PE', ['mft', 'ape', 'ald', 'aop', 'atg', 'mbp', 'lhc', 'blp',
    'ibp', 'tcg', 'pcl', 'ctf', 'chm', 'tgi', 'cix', 'ayp', 'ans', 'ata', 'umi',
    'lim', 'sfk', 'ucz', 'rij', 'jji', 'jau', 'jul', 'sja', 'cja', 'rim', 'ilq',
    'lim', 'tbp', 'chm', 'smg', 'yms', 'huu', 'squ', 'syc', 'chh', 'req', 'iqt',
    'aqp', 'tru', 'sqd', 'pio', 'tpp', 'syc', 'tcq', 'pem', 'piu', 'tyl', 'nza',
    'cuz', 'vvn']],
  ['PF', ['ppt', 'rur', 'tub', 'aaa', 'fgu', 'tih', 'apk', 'rea',
    'fav', 'hhz', 'xmh', 'gmr', 'kkr', 'mkp', 'nau', 'tkv', 'pkp', 'puk', 'tkp',
    'axr', 'mvt', 'nuk', 'zta', 'ahe', 'khz', 'fac', 'fhz', 'tkx', 'nhv', 'auq',
    'uap', 'uah', 'bob', 'tti', 'rgi', 'huh', 'moz', 'hoi', 'mau', 'rfp', 'vhz']],
  ['PG', ['abp', 'adc', 'aek', 'afr', 'agg', 'agk', 'agl', 'aie', 'aih', 'amf',
    'amu', 'aob', 'app', 'apr', 'arp', 'asz', 'atp', 'aui', 'auj', 'aup', 'auv',
    'bua', 'cmu', 'dau', 'gka', 'gur', 'pnp', 'hkn', 'lsa', 'ung', 'kri', 'kma',
    'kvg', 'lnv', 'mag', 'hgu', 'mdu', 'mas', 'mxh', 'mis', 'lae', 'pom', 'tiz',
    'tbg', 'rab', 'ayu', 'vai', 'wbm', 'wwk', 'azb', 'fin', 'krj', 'akg', 'awb',
    'baa', 'cvb', 'gmi', 'gvi', 'hyf', 'ihu', 'iis', 'jaq', 'kdr', 'kkd', 'kuy',
    'kwo', 'kxr', 'lmi', 'lmy', 'obx', 'opu', 'skc', 'tfi', 'tfm', 'tlo', 'uku',
    'ule', 'vmu', 'wpm', 'raw', 'uae']],
  ['PH', ['eni', 'sfs', 'crk', 'lao', 'mnl',
    'cyu', 'lgp', 'nsp', 'lbx', 'aav', 'ges', 'cbo', 'dvo', 'bxu', 'bph', 'dpl',
    'cgm', 'ign', 'jol', 'cgy', 'mlp', 'sgs', 'ozc', 'pag', 'mxi', 'sug', 'cdy',
    'ipe', 'tdg', 'zam', 'iao', 'bag', 'dte', 'sji', 'mbo', 'wnp', 'bso', 'bqa',
    'sfe', 'tug', 'vrc', 'mrq', 'cyz', 'tac', 'bcd', 'cyp', 'dgt', 'mph', 'crm',
    'gui', 'ilo', 'mbt', 'klo', 'ceb', 'omc', 'pps', 'rxs', 'euq', 'tag', 'tbh',
    'usu', 'bpr', 'bcd']],
  ['PK', ['ddu', 'aaw', 'bnp', 'wgb', 'bhv', 'cjl', 'chb',
    'dba', 'ddu', 'dea', 'dsk', 'lyp', 'gwd', 'gil', 'jag', 'jiw', 'khi', 'hdd',
    'kdd', 'kbh', 'oht', 'lhe', 'lrg', 'xjm', 'mfg', 'mwd', 'mjd', 'mpd', 'mpd',
    'mux', 'wns', 'nhs', 'orw', 'paj', 'pjg', 'psi', 'pew', 'uet', 'ryk', 'isb',
    'raz', 'sbq', 'kdu', 'skz', 'syw', 'sgi', 'sdt', 'skt', 'sul', 'swn', 'tlb',
    'bdn', 'tft', 'tuk', 'waf', 'pzh', 'bhc', 'cwp', 'grt', 'hra', 'kcf', 'req',
    'rzs', 'swv', 'ziz']],
  ['PL', ['qyy', 'bzg', 'czw', 'gdn', 'qlc', 'krk', 'osz',
    'ktw', 'qeo', 'lcj', 'qlu', 'qws', 'qyd', 'qpm', 'poz', 'rze', 'szz', 'osp',
    'szy', 'waw', 'wro', 'ieg']],
  ['PM', ['mqc', 'fsp']],
  ['PR', ['tjp', 'mjg',
    'ddp', 'huc', 'ppd', 'are', 'bqn', 'vqs', 'cpx', 'faj', 'sig', 'maz', 'pse',
    'sju']],
  ['PS', ['ghk', 'jrs', 'gza', 'jrs']],
  ['PT', ['sma', 'bgc', 'byj',
    'bgz', 'chv', 'cbp', 'cvu', 'cov', 'flw', 'fao', 'grw', 'hor', 'ter', 'fnc',
    'paf', 'pdl', 'pix', 'prm', 'opo', 'pxo', 'lis', 'sie', 'sjz', 'vrl', 'vse']],
  ['PW', ['ror']],
  ['PY', ['bfa', 'olk', 'pbt', 'pcj', 'asu', 'ayo', 'cio', 'eno',
    'agt', 'flm', 'esg', 'pil', 'pjc', 'vmi']],
  ['QA', ['doh', 'iud']],
  ['RE',
    ['run', 'zse']],
  ['RO', ['arw', 'bcm', 'bay', 'bbu', 'cnd', 'clj', 'csb', 'cra',
    'ias', 'omr', 'otp', 'sbz', 'suj', 'scv', 'tce', 'tgm', 'tsr']],
  ['RS', ['uzc',
    'beg', 'ljb', 'bjy', 'kid', 'ini', 'qnd']],
  ['RU', ['ngk', 'grv', 'lnx', 'vus',
    'adh', 'yks', 'cnn', 'ulk', 'pyj', 'mjz', 'ckh', 'cyx', 'iks', 'enk', 'bqs',
    'gdg', 'tyd', 'khv', 'kxk', 'dyr', 'pvs', 'gdx', 'pwe', 'bqg', 'oho', 'pkc',
    'ohh', 'eks', 'dee', 'zzo', 'uus', 'vvo', 'hta', 'btk', 'uik', 'ikt', 'odo',
    'erg', 'ukx', 'uud', 'arh', 'nnm', 'csh', 'cee', 'amv', 'ksz', 'led', 'kvk',
    'mmk', 'nvr', 'vlu', 'pkv', 'pes', 'rvh', 'vgd', 'kgd', 'aba', 'bax', 'kej',
    'eie', 'kja', 'acs', 'kyz', 'ovb', 'oms', 'tof', 'noz', 'dks', 'htg', 'iaa',
    'nsk', 'aaq', 'eik', 'gdz', 'krr', 'mcx', 'mrv', 'nal', 'ogz', 'igt', 'stw',
    'rov', 'vlk', 'aer', 'asf', 'esl', 'vog', 'cek', 'mqf', 'sly', 'ymk', 'uen',
    'ezv', 'hma', 'irm', 'nya', 'ovs', 'urj', 'eyk', 'ijk', 'kvx', 'nym', 'nux',
    'njc', 'rat', 'pee', 'kgp', 'nfg', 'noj', 'sgc', 'svx', 'tox', 'tjm', 'kro',
    'kmw', 'bka', 'iwa', 'ryb', 'bzk', 'dme', 'iar', 'svo', 'kld', 'ego', 'urs',
    'lpk', 'voz', 'oel', 'tbw', 'rzn', 'vko', 'uct', 'ina', 'pex', 'usk', 'vkt',
    'uts', 'scw', 'goj', 'uua', 'kzn', 'nbc', 'jok', 'csy', 'ulv', 'uly', 'ren',
    'osw', 'pez', 'skx', 'bwo', 'rtw', 'bcx', 'nef', 'okt', 'ufa', 'kuf']],
  ['RW',
    ['gyi', 'btq', 'kgl', 'rhg', 'kme']],
  ['SA', ['ahb', 'hof', 'abt', 'bhh', 'dmm',
    'dha', 'dwd', 'giz', 'elq', 'ury', 'has', 'qjb', 'jed', 'hbt', 'kmx', 'med',
    'eam', 'aqi', 'akh', 'rah', 'ruh', 'rae', 'xxn', 'shw', 'ajf', 'slf', 'tuu',
    'tif', 'tui', 'ewd', 'ejh', 'ynb', 'zul', 'ulh']],
  ['SB', ['aft', 'atd', 'vev',
    'gef', 'aks', 'bas', 'fre', 'hir', 'mbu', 'ira', 'scz', 'mua', 'gzo', 'mny',
    'prs', 'otv', 'rnl', 'egm', 'rus', 'vao', 'kge', 'rin', 'rbv', 'anh', 'viu',
    'gta']],
  ['SC', ['des', 'sez', 'pri', 'bdi', 'dei', 'frk', 'pri', 'pri']],
  ['SD', ['bje', 'atb', 'edb', 'dog', 'elf', 'gsu', 'dnx', 'egn', 'ksl', 'gbu',
    'kst', 'kdx', 'mwe', 'nud', 'uyl', 'nhf', 'ebd', 'pzu', 'krt', 'whf']],
  ['SE',
    ['rnb', 'xwp', 'got', 'jkg', 'ldk', 'gse', 'kvb', 'thn', 'ksk', 'mxx', 'nyo',
      'kid', 'osk', 'klr', 'mmx', 'had', 'vxo', 'evg', 'gev', 'huv', 'krf', 'lyc',
      'sdl', 'oer', 'krn', 'sft', 'ume', 'vhm', 'ajr', 'soo', 'osd', 'orb', 'hfs',
      'ksd', 'vst', 'lla', 'arn', 'bma', 'ble', 'hlf', 'gvx', 'lpi', 'nrk', 'tyf',
      'ekt', 'vby', 'vvk', 'agh', 'sqo', 'idb', 'pja', 'hmv']],
  ['SG', ['qpg', 'tga',
    'xsp', 'sin']],
  ['SH', ['asi']],
  ['SI', ['lju', 'mbx', 'pow']],
  ['SK', ['bts',
    'ksc', 'lue', 'pzy', 'pov', 'sld', 'ilz']],
  ['SL', ['bte', 'kbs', 'gbk', 'hgs',
    'kba', 'ken', 'fna', 'wye']],
  ['SN', ['kda', 'zig', 'csk', 'klc', 'dkr', 'max',
    'pod', 'rdt', 'xls', 'bxe', 'kgg', 'smy', 'tud']],
  ['SO', ['alu', 'bib', 'cxn',
    'hcm', 'bsa', 'gsr', 'hga', 'bbo', 'kmu', 'mgq', 'cmo', 'glk', 'cms', 'era',
    'buo', 'bxx']],
  ['SR', ['bto', 'doe', 'ldo', 'wso', 'abn', 'tot', 'drj', 'pbm',
    'ick', 'oem', 'smz', 'agi', 'org', 'aaj', 'kcb']],
  ['SS', ['aee', 'hgi', 'jub',
    'mak', 'wuu']],
  ['ST', ['pcp', 'tms']],
  ['SV', ['sal']],
  ['SY', ['alp', 'dam',
    'dez', 'kac', 'ltk', 'pms']],
  ['SZ', ['mts']],
  ['TC', ['gdt', 'mds', 'nca',
    'pic', 'pls', 'xsc', 'slx']],
  ['TD', ['akm', 'srh', 'ogr', 'aeh', 'mqq', 'ltc',
    'atv', 'ndj', 'bkr', 'otc', 'mvo', 'amc', 'plf', 'out', 'amo', 'fyt']],
  ['TG',
    ['lrl', 'lfw']],
  ['TH', ['dmk', 'kkm', 'kkm', 'tdx', 'bkk', 'utp', 'cnx', 'hgn',
    'pyy', 'lpt', 'nnt', 'prh', 'cei', 'bao', 'phy', 'hhq', 'tkh', 'maq', 'ths',
    'phs', 'tkt', 'utr', 'urt', 'naw', 'cjm', 'nst', 'kbv', 'sgz', 'pan', 'usm',
    'nst', 'hkt', 'unn', 'hdy', 'tst', 'uth', 'sno', 'kkc', 'loe', 'bfv', 'nak',
    'ubp', 'roi', 'kop']],
  ['TJ', ['dyu', 'tju', 'lbd', 'kqt']],
  ['TL', ['kci',
    'aut', 'uai', 'dic', 'dil', 'bch', 'mpt', 'oec', 'viq']],
  ['TM', ['asb', 'krw',
    'myp', 'taz', 'crz']],
  ['TN', ['tbj', 'mir', 'tun', 'oiz', 'gaf', 'gae', 'dje',
    'ebm', 'sfa', 'toe', 'nbe']],
  ['TO', ['eua', 'tbu', 'hpa', 'nfo', 'ntt',
    'vav']],
  ['TR', ['gkd', 'esb', 'ank', 'ada', 'uab', 'afy', 'ayt', 'gzt', 'isk',
    'kfs', 'kya', 'mzh', 'ssx', 'vas', 'onq', 'mlx', 'asr', 'tjk', 'dnz', 'nav',
    'ist', 'btz', 'bzi', 'bdm', 'ckz', 'esk', 'adb', 'igl', 'usq', 'kco', 'yei',
    'dlm', 'teq', 'bxn', 'aoe', 'ezs', 'diy', 'erc', 'erz', 'ksy', 'tzx', 'sfq',
    'van', 'bal', 'msr', 'sxz', 'sic', 'kcm', 'aji', 'adf', 'mqm', 'gny', 'hty',
    'ise', 'edo', 'bjv', 'szf', 'saw', 'gzp']],
  ['TT', ['tab', 'pos']],
  ['TV',
    ['fun']],
  ['TW', ['knh', 'lzn', 'ttt', 'gni', 'khh', 'cyi', 'hcn', 'txg', 'kyd',
    'rmq', 'mfk', 'tnn', 'mzg', 'pif', 'tsa', 'tpe', 'wot', 'hun', 'cmj']],
  ['TZ',
    ['gtz', 'ark', 'bkz', 'dar', 'dod', 'iri', 'tkq', 'kiy', 'jro', 'ldi', 'lky',
      'mfa', 'mbi', 'mwn', 'xmi', 'qsi', 'myw', 'muz', 'mwz', 'nch', 'jom', 'pma',
      'seu', 'sgx', 'sut', 'shy', 'tbo', 'tgt', 'znz', 'git', 'luy']],
  ['UA', ['kbp',
    'dok', 'krq', 'mpw', 'sev', 'vsg', 'erd', 'dnk', 'ozh', 'kwg', 'uks', 'sip',
    'khc', 'hrk', 'plv', 'umy', 'ckc', 'kgo', 'iev', 'gml', 'uck', 'hmj', 'ifo',
    'lwo', 'cwc', 'rwn', 'tnl', 'udj', 'khe', 'nlv', 'ods', 'vin']],
  ['UG', ['rua',
    'ebb', 'ulu', 'jin', 'kbg', 'kse', 'mbq', 'kcu', 'srt', 'try', 'oyg']],
  ['UM',
    ['jon', 'mdy', 'awk']],
  ['US', ['fiv', 'fak', 'bws', 'wkk', 'tss', 'fob', 'aht',
    'aos', 'alz', 'aqy', 'ayz', 'cdk', 'cga', 'clg', 'dhb', 'exi', 'few', 'gnu',
    'jmc', 'jra', 'amk', 'rla', 'fid', 'ahd', 'gcw', 'rkc', 'gnf', 'ahf', 'gtp',
    'gcd', 'fpy', 'fhb', 'bld', 'aaf', 'abe', 'abi', 'abq', 'abr', 'aby', 'acb',
    'ack', 'act', 'acv', 'acy', 'adg', 'adt', 'adm', 'ads', 'adw', 'kae', 'ael',
    'aex', 'aff', 'wsg', 'afn', 'afo', 'afw', 'agc', 'ago', 'ags', 'ahc', 'ahh',
    'ahn', 'aia', 'aid', 'aik', 'aio', 'aiv', 'aiy', 'aiz', 'ako', 'akc', 'alb',
    'ali', 'alm', 'aln', 'alo', 'als', 'alw', 'alx', 'ama', 'amn', 'amw', 'anb',
    'and', 'anp', 'anq', 'anw', 'any', 'aoh', 'aoo', 'apa', 'apc', 'apf', 'apg',
    'aph', 'apn', 'apt', 'apv', 'ara', 'arb', 'arg', 'art', 'atl', 'atw', 'aty',
    'aug', 'aus', 'avl', 'avo', 'avp', 'awm', 'axn', 'axs', 'axv', 'axx', 'aye',
    'ays', 'azo', 'bab', 'bad', 'baf', 'bdl', 'bdr', 'bed', 'bfd', 'bff', 'bfi',
    'bfl', 'bgm', 'bgr', 'bhb', 'bhm', 'bil', 'bis', 'bkl', 'bkw', 'bkx', 'blf',
    'bli', 'bmg', 'bmi', 'bmt', 'bna', 'boi', 'bos', 'bpt', 'bqk', 'brl', 'bro',
    'btm', 'btr', 'btv', 'bty', 'bub', 'buf', 'bum', 'bur', 'bvo', 'bvx', 'bvy',
    'bwc', 'bwd', 'bwg', 'bwi', 'bxa', 'bxk', 'bys', 'bzn', 'clg', 'cae', 'cak',
    'cdc', 'cec', 'cef', 'cgi', 'cgx', 'cha', 'cho', 'chs', 'cid', 'ciu', 'ckb',
    'kcl', 'cle', 'cll', 'clm', 'clt', 'cmh', 'cmi', 'cmx', 'cnm', 'cos', 'cou',
    'cpr', 'cro', 'crp', 'crw', 'csg', 'cvg', 'kip', 'cwf', 'cys', 'dab', 'dal',
    'dan', 'day', 'dbq', 'dca', 'ddc', 'dec', 'den', 'det', 'dfw', 'dhn', 'dlh',
    'dnl', 'dsm', 'dtw', 'duj', 'ale', 'bgt', 'ear', 'eau', 'ecp', 'een', 'ege',
    'kek', 'eko', 'eld', 'elm', 'elp', 'eri', 'eug', 'evv', 'ewb', 'ewn', 'ewr',
    'eyw', 'far', 'fat', 'fay', 'fbg', 'fcs', 'frd', 'fhu', 'flg', 'fll', 'flo',
    'flu', 'fnt', 'fod', 'foe', 'fil', 'fpr', 'frh', 'fri', 'frm', 'fsd', 'fsm',
    'fms', 'ftw', 'fwa', 'fyv', 'gck', 'gcn', 'geg', 'gfk', 'ggg', 'ggw', 'gjt',
    'glh', 'gls', 'gnv', 'gon', 'fca', 'gpt', 'grb', 'gri', 'grk', 'grr', 'gso',
    'gsp', 'gtf', 'gup', 'gvt', 'gvw', 'gyy', 'hgr', 'hib', 'hky', 'hln', 'hon',
    'hot', 'hou', 'hpn', 'hrl', 'hro', 'hnc', 'hsv', 'hts', 'huf', 'hvn', 'hya',
    'iab', 'iad', 'iag', 'iah', 'ict', 'ida', 'ifp', 'igm', 'ilg', 'ilm', 'ind',
    'inl', 'int', 'ipt', 'irk', 'isp', 'ith', 'aza', 'jac', 'jan', 'jax', 'jbr',
    'jfk', 'jln', 'jms', 'jst', 'laf', 'lan', 'lar', 'las', 'lax', 'lbb', 'lbe',
    'lbf', 'lbl', 'lch', 'leb', 'lex', 'lft', 'lga', 'lgb', 'lhc', 'lit', 'lmt',
    'lnk', 'lns', 'lrd', 'lru', 'lse', 'luk', 'lws', 'lwt', 'lyh', 'maf', 'mbs',
    'mce', 'mci', 'mcn', 'mco', 'mdh', 'mdt', 'mdw', 'mei', 'mem', 'mfe', 'mfr',
    'mgm', 'mgw', 'mhk', 'mht', 'mia', 'mie', 'mkc', 'mke', 'mkg', 'mkl', 'mlb',
    'mli', 'mls', 'mlu', 'mmu', 'mob', 'mod', 'mot', 'mry', 'msl', 'msn', 'mso',
    'msp', 'mss', 'msy', 'mvy', 'myr', 'nel', 'ngz', 'nop', 'yum', 'nvn', 'odc',
    'oak', 'oar', 'okc', 'old', 'olm', 'oma', 'ont', 'ord', 'orf', 'orh', 'osh',
    'oth', 'otm', 'owb', 'hbk', 'cwx', 'pae', 'pah', 'pbg', 'pbi', 'pca', 'pdk',
    'pdx', 'pfn', 'phf', 'adr', 'phl', 'phx', 'pia', 'pib', 'pie', 'pih', 'pir',
    'pit', 'pkb', 'plb', 'pln', 'pmd', 'pns', 'pou', 'pqi', 'prc', 'psc', 'psm',
    'psp', 'pub', 'puw', 'pvd', 'pwm', 'pwt', 'kqa', 'rap', 'rdd', 'rdg', 'rdm',
    'rdu', 'rfd', 'rhi', 'ric', 'rks', 'rno', 'roa', 'roc', 'row', 'rqo', 'rst',
    'rsw', 'rut', 'rwi', 'ahm', 'suo', 'idh', 'vsk', 'san', 'sat', 'sav', 'sba',
    'sbn', 'sbp', 'sby', 'sdf', 'sea', 'sfb', 'sfo', 'sgf', 'shd', 'shr', 'shv',
    'sjc', 'sjt', 'slc', 'slk', 'sln', 'smf', 'smx', 'sna', 'spi', 'sps', 'srq',
    'stc', 'stl', 'stp', 'sun', 'sux', 'svc', 'swf', 'syr', 'tbn', 'tcl', 'tlh',
    'otk', 'tol', 'tpa', 'tpl', 'tri', 'ttn', 'tul', 'tup', 'tus', 'tvc', 'tvl',
    'twf', 'txk', 'tyr', 'tys', 'ics', 'uca', 'uin', 'uiz', 'sce', 'vct', 'vld',
    'vps', 'vrb', 'wri', 'wrl', 'yip', 'ykm', 'yng', 'avx', 'lor', 'lro', 'mdr',
    'o62', 'bzf', 'obk', 'akb', 'ptd', 'paq', 'bti', 'bet', 'bvu', 'big', 'bkc',
    'brw', 'btt', 'cdb', 'clf', 'cdv', 'czf', 'drg', 'adk', 'dlg', 'adq', 'dut',
    'edf', 'eek', 'ehm', 'eil', 'enm', 'ena', 'fai', 'fbk', 'afe', 'abl', 'frn',
    'fmc', 'gal', 'gkn', 'gam', 'agn', 'gst', 'sgy', 'hcr', 'hns', 'hom', 'hpb',
    'hyg', 'igg', 'eii', 'ian', 'ili', 'uto', 'jnu', 'kfp', 'akk', 'akn', 'iko',
    'akp', 'ktn', 'kal', 'akw', 'klg', 'lur', 'mcg', 'mou', 'mri', 'myu', 'wna',
    'anc', 'ani', 'enn', 'ann', 'anv', 'knw', 'pca', 'hnh', 'ome', 'ort', 'otz',
    'pbv', 'kpc', 'psg', 'pth', 'ptu', 'pho', 'nui', 'arc', 'rby', 'sva', 'scc',
    'sdp', 'shh', 'sit', 'ksm', 'snp', 'svw', 'sxq', 'sya', 'tog', 'tkj', 'tlj',
    'atk', 'vak', 'kvc', 'vdz', 'kvl', 'swd', 'wrg', 'ain', 'wtk', 'iys', 'aki',
    'aet', 'fyu', 'bkh', 'hdh', 'hhi', 'hnm', 'jhm', 'jrf', 'koa', 'lih', 'lup',
    'mkk', 'mue', 'hnl', 'lny', 'ogg', 'ito', 'upp', 'piz', 'lps', 'szn', 'twh',
    'ugb', 'aht', 'fbs', 'wwt']],
  ['UY', ['ati', 'buv', 'cyr', 'car', 'dzo', 'pdp',
    'mer', 'mlz', 'mvd', 'mdo', 'pdu', 'rvy', 'sty', 'taw', 'tyt', 'vch', 'fzb',
    'rch']],
  ['UZ', ['azn', 'feg', 'nma', 'ncu', 'ugc', 'nvi', 'bhk', 'ksq', 'afs',
    'skd', 'tmj', 'tas']],
  ['VC', ['bqu', 'ciw', 'mqs', 'uni', 'svd']],
  ['VE',
    ['agv', 'aao', 'lpj', 'bla', 'bns', 'elr', 'brm', 'myc', 'cbl', 'cxa', 'cuv',
      'clz', 'caj', 'vcr', 'cup', 'cze', 'cum', 'isl', 'eor', 'eoz', 'gdo', 'gui',
      'guq', 'ica', 'lsp', 'kav', 'lfr', 'mar', 'mrd', 'pmv', 'ccs', 'mun', 'cbs',
      'pyh', 'pbl', 'pdz', 'pph', 'sci', 'pzo', 'ptm', 'lrv', 'svz', 'sbb', 'snv',
      'std', 'snf', 'sfd', 'som', 'stb', 'tuv', 'tmo', 'urm', 'vln', 'vig', 'vlv',
      'vdp', 'elx', 'lgy', 'ktv', 'lag', 'sfx', 'svv', 'wok']],
  ['VG', ['ngd', 'eis',
    'vij']],
  ['VI', ['stt', 'stx', 'spb', 'ssb']],
  ['VN', ['vdh', 'kon', 'bmv',
    'vcl', 'hph', 'cxr', 'vcs', 'vca', 'din', 'dli', 'dad', 'han', 'sqh', 'nha',
    'hui', 'uih', 'pxu', 'pqc', 'pha', 'phh', 'vkg', 'tbb', 'sgn', 'vii', 'vtg']],
  ['VU', ['mtv', 'slh', 'toh', 'eae', 'ccv', 'lod', 'ssr', 'pbj', 'lpm', 'lnb',
    'mwf', 'lne', 'nus', 'zgu', 'rcl', 'son', 'tgh', 'ulb', 'vls', 'wlh', 'swj',
    'olj', 'auy', 'awd', 'dly', 'fta', 'ipa', 'uiq', 'vli', 'tah']],
  ['WF', ['fut',
    'wls']],
  ['WS', ['aau', 'apw', 'fgi', 'mxs']],
  ['YE', ['ade', 'eab', 'axk',
    'bhn', 'aay', 'hod', 'myn', 'ihn', 'riy', 'sye', 'sah', 'sct', 'gxf', 'tai',
    'wda']],
  ['YT', ['dza']],
  ['ZA', ['alj', 'agz', 'ady', 'biy', 'bfn', 'ute',
    'cdo', 'cpt', 'duk', 'pzl', 'els', 'emg', 'ell', 'fcb', 'gcj', 'grj', 'giy',
    'qra', 'hlw', 'hrs', 'hds', 'jnb', 'kxe', 'kim', 'mqp', 'kof', 'kmh', 'klz',
    'hla', 'lmr', 'ldz', 'dur', 'luj', 'lcd', 'lge', 'lay', 'aam', 'mgh', 'mbd',
    'lle', 'mzy', 'mez', 'mzq', 'ncs', 'ngl', 'nlp', 'ovg', 'ouh', 'afd', 'plz',
    'pbz', 'phw', 'ptg', 'joh', 'prk', 'pzb', 'nty', 'ptg', 'pcf', 'utw', 'rcb',
    'rvo', 'rod', 'sbu', 'zec', 'sdb', 'gss', 'sis', 'szk', 'thy', 'tcu', 'lta',
    'uld', 'utn', 'utt', 'vru', 'vir', 'vre', 'vyd', 'pry', 'afb', 'wel', 'hpr',
    'ulx', 'tdt', 'hzv', 'kho', 'mbm', 'iny', 'tsd', 'kig']],
  ['ZM', ['mmq', 'cip',
    'zkp', 'klb', 'kmz', 'kaa', 'zkb', 'lvi', 'lxu', 'lun', 'mns', 'mfu', 'mnr',
    'zgm', 'nla', 'sxg', 'kiw', 'sjq', 'sli', 'bbz', 'cgj']],
  ['ZW', ['buq', 'chj',
    'bfo', 'vfa', 'hre', 'kab', 'uta', 'mvz', 'gwe', 'hwn', 'wki']]
]

let MLAB_LOC_TO_COUNTRY = {}
AIRPORTS_PER_COUNTRY.forEach((row) => {
  const [ countryCode, airportCodes ] = row
  airportCodes.forEach((airportCode) => {
    MLAB_LOC_TO_COUNTRY[airportCode] = countryCode
  })
})

export const mlabServerToCountry = (serverAddress) => {
  return MLAB_LOC_TO_COUNTRY[serverAddress.split('.')[3].substr(3)]
}

export const mlabServerToName = (serverAddress) => {
  return serverAddress.split('.').slice(3, 4).join('.')
}
