import { colors } from 'ooni-components'

const okColor = colors.green['300']

export const blockingTypeColors = {
  dns_isp: {
    ok: okColor,
    blocked: colors.violet['700'],
    down: colors.violet['300'],
  },
  dns_other: {
    ok: okColor,
    blocked: colors.fuchsia['700'],
    down: colors.fuchsia['300'],
  },
  tls: {
    ok: okColor,
    blocked: colors.orange['700'],
    down: colors.orange['300'],
  },
  tcp: {
    ok: okColor,
    blocked: colors.indigo['700'],
    down: colors.indigo['300'],
  },
}

export const colorMap = {
  confirmed_count: colors.red['700'],
  anomaly_count: colors.yellow['500'],
  failure_count: colors.gray['400'],
  ok_count: colors.green['500'],
  measurement_count: colors.blue['500'],
  outcome_blocked: colors.red['700'],
  outcome_down: colors.yellow['500'],
  outcome_ok: colors.green['500'],
  'dns_isp.down': blockingTypeColors.dns_isp.down,
  'dns_isp.blocked': blockingTypeColors.dns_isp.blocked,
  'dns_isp.ok': blockingTypeColors.dns_isp.ok,
  'dns_other.down': blockingTypeColors.dns_other.down,
  'dns_other.blocked': blockingTypeColors.dns_other.blocked,
  'dns_other.ok': blockingTypeColors.dns_other.ok,
  'tls.down': blockingTypeColors.tls.down,
  'tls.blocked': blockingTypeColors.tls.blocked,
  'tls.ok': blockingTypeColors.tls.ok,
  'tcp.down': blockingTypeColors.tcp.down,
  'tcp.blocked': blockingTypeColors.tcp.blocked,
  'tcp.ok': blockingTypeColors.tcp.ok,
  ok: blockingTypeColors.tls.ok,
  // 'tls.blocked.connection_reset': colors.fuchsia['700'],
  // 'tls.blocked.connection_aborted': colors.pink['600'],
  // 'tls.blocked.generic_timeout_error': colors.red['900'],
  // 'tls.blocked.ssl_invalid_hostname': colors.yellow['600'],
  // 'tls.blocked.unknown_failure': colors.fuchsia['200'],
  // 'tls.blocked.invalid_record': colors.pink['200'],
  // 'tls.blocked.eof_error': colors.pink['400'],
  // 'tls.blocked.access_denied': colors.pink['600'],
  // 'tls.down.connection_reset': colors.yellow['300'],
  // 'tls.down.access_denied': colors.yellow['300'],
  // 'tls.down.ssl_unknown_authority': colors.yellow['300'],
  // 'tls.down.ssl_invalid_certificate': colors.yellow['300'],
  // 'tls.down.ssl_invalid_hostname': colors.yellow['300'],
  // 'tcp.blocked.connection_refused': colors.yellow['300'],
  // 'tcp.blocked.generic_timeout_error': colors.yellow['800'],
  // 'tcp.down.generic_timeout_error': colors.yellow['400'],
  // 'tcp.down.connection_refused': colors.yellow['400'],
  // 'tcp.down.address_not_available': colors.yellow['400'],
  // 'dns_isp.': colors.blue['500'],
  // 'dns_isp.blocked.generic_timeout_error': colors.blue['800'],
  // 'dns_isp.blocked.dns_server_misbehaving': colors.blue['800'],
  // 'dns_isp.blocked.got_answer': colors.blue['200'],
  // 'dns_isp.blocked.nxdomain': colors.blue['800'],
  // 'dns_isp.down.generic_timeout_error': colors.blue['400'],
  // 'dns_isp.down.dns_temporary_failure': colors.blue['600'],
  // 'dns_isp.down.nxdomain': colors.blue['600'],
  // 'dns_isp.down.dns_no_answer': colors.blue['800'],
  // 'dns_other.down.nxdomain': colors.cyan['600'],
  // 'dns_other.blocked.nxdomain': colors.cyan['200'],
  // 'dns_other.blocked.got_answer': colors.cyan['600'],
  // 'dns_other.blocked.dns_server_misbehaving': colors.cyan['800'],
  // 'dns_other.blocked.dns_no_answer': colors.cyan['800'],
  // 'dns_other.down.dns_server_misbehaving': colors.cyan['400'],
}
